### ISSUE TITLE
Error when adding a category

### ISSUE THREAD

**Issue by martijnimhoff** [aimeos/ai-admin-jqadm#10]
Laravel 5.4
Aimeos 2017.07

--
Hi there,
I'm new to the Aimeos package. I'm currently looking for a simple and fast Laravel package to built webshops for my client at work and perhaps some personal projects :) and one that is OS, I hope I have enough development skills to be able to contribute to it. (Perhaps I can apply my usability skills)

I'm going through the product tutorial: https://aimeos.org/docs/User_Manual/Create_the_first_product
And I'm running into a problem when adding a new category (BTW: the 'add a category' button in the "ai-admin-jqadm" interface is hard to find). I add a new category by hitting "save and new". Then I fill in the Code and Label field, hit save and this gives the following error:

```
Fout No node with ID "0" found, /home/vagrant/valemus-shop/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Tree/Manager/DBNestedSet.php:782
```

How can I fix this?

**Comment by aimeos** [comment]
Suggestions are always welcome! :-)
Thanks for the hint, we will fix the bug, improve the buttons and come back to you when it's done

**Comment by aimeos** [comment]
The bug was already fixed but not yet released. If you execute `composer update`, it should be gone.

**Comment by aimeos** [comment]
The button for adding a new category will be blue like the save button in the next version.
Thank you for mentioning :-)
