### ISSUE TITLE
Stock DB entry not deleted on code update

### ISSUE THREAD

**Issue by nvindice** [aimeos/ai-admin-jqadm#109]
**Environment**
1. Version: 2018.10
2. Integration: TYPO3
3. System: Linux

**Describe the bug**
When a product's SKU has been used before, the product can not be saved because of a DB integrity violation. See Context.

**To Reproduce**
1. Create a product with SKU "AAA", save it
2. Change the product's SKU to "BBB", save it
3. Create a new product with SKU "AAA" -> Error

**Expected behavior**
Products with all SKUs currently not in use should be saved.

**Additional context**
When saving a product with a new SKU, a new stock entry is created in mshop_stock, but the old one is not deleted. This leads to the integrity constraint violation.

**Comment by aimeos** [comment]
The best option would be if the stock entries will be renamed too but there's no way to track that because they are independent from the products and the old SKU isn't available in the product stock class which could do that. Not sure how this could be solved ...

**Comment by aimeos** [comment]
The problem has been solved by storing the product ID instead of the product code in the mshop_stock table. This will be part of the 2021.x releases.
