### ISSUE TITLE
tree structure : moving categories not possible

### ISSUE THREAD

**Issue by ulgerman** [aimeos/ai-admin-jqadm#11]
Hey,

When I try to drag-and-drop categories to a new hierarchy location , I see the suggestion for the drop,
but when I try to drop , nothing changes.

Here is some additional info I retrieved from webdeveloper

PATCH XHR /admin/default/jsonadm/catalog?id=6
RAW DATA  {"data":{"attributes":{},"id":"6","parentid":"1","targetid":"1"}}
response code : 500 internal server error

Thanx for looking in to this
johan

**Comment by aimeos** [comment]
In the admin interface it works well:
http://admin.demo.aimeos.org/admin/default/jqadm/search/catalog?lang=en

Can you please make sure you have the latest version installed (run composer update). There was a bug we fixed two days before that looks like your problem too.

**Comment by ulgerman** [comment]
OK did run composer update and it's working fine now.

Thanx
