### ISSUE TITLE
Replace remove button with an edit button or a dropdown with different actions 

### ISSUE THREAD

**Issue by SamiXSous** [aimeos/ai-admin-jqadm#110]
**Is your feature request related to a problem?**
When I want to disable multiple languages I can select the languages I want to disable, but there is no edit button for multiple languages. Only delete option

**Describe the solution you'd like**
It would be nice and time saving to have a feature that you could enable or disable all selected languages

**Describe alternatives you've considered**
Instead of having the "X" button that can only delete language have a dropdown to choose which action you would like to perform

**Additional context**
![Screenshot 2020-03-12 at 10 20 00 AM](https://user-images.githubusercontent.com/10419603/76506583-b0d07e00-644b-11ea-8091-eb3cab565a21.png)

**Comment by aimeos** [comment]
Thank you for your feature request.
Editing multiple items at once is hard to implement but activating or deactivating the selected items at once should be possible. We will see how we can implement that in one of the next versions.

**Comment by aimeos** [comment]
Done. Beginning with 2022.07, it's possible to edit items in batches
