### ISSUE TITLE
Responsive/Mobile User Interface/Experience

### ISSUE THREAD

**Issue by superscotty19** [aimeos/ai-admin-jqadm#112]
Shopify and SquareSpace are littering social feeds. It's time that Aimeos becomes the most talked about e-commerce system!!! Moreover, I'm reading countless testimonials of people "managing their inventory while they sit on the toilet" (using their phone), so clearly a mobile-first design is only going to be more and more important.

If you look at the current interface (screenshots attached to state the obvious), it works "OK", but the sidebar isn't intuitive (I wouldn't immediately know how to access products if I didn't know which icon corresponded), and the pages themselves have well-styled content but the top headings are a little jammed up.

![Screenshot_2020-04-21 Dutch Cycle Lightning  TYPO3 CMS 8 7 4](https://user-images.githubusercontent.com/12812378/79926973-89ca7c00-83fb-11ea-9331-bdf2a009c448.png)
![Screenshot_2020-04-21 Dutch Cycle Lightning  TYPO3 CMS 8 7 4 2](https://user-images.githubusercontent.com/12812378/79926974-8a631280-83fb-11ea-9dc0-fe28e0bd9ee7.png)

Would it be possible to have the menu expand to display words on mobile? Or perhaps hide it entirely and have a slide-out menu on click of a button?

I'm trying to find screenshots of what Wix, SquareSpace, and Shopify look like on mobile but I'm coming up short.

At this point, I'm just doing some competitive analysis and reporting what I find. I want to grow Aimeos and/or help any way I can.
-Scott.

**Comment by aimeos** [comment]
Thank you for your suggestion. The mobile experience of the admin backend could be improved for sure. We will see when we can care about

**Comment by aimeos** [comment]
Thanks to Robert, the navigation and header is now much more mobile friendly
