### ISSUE TITLE
Deleting languages or currencies in the backend module doesnt work

### ISSUE THREAD

**Issue by linawolf** [aimeos/ai-admin-jqadm#113]
**Environment**
1. Version "aimeos/aimeos-typo3": "^18.4"
2. Integration TYPO3 8.7.33 installed via composer
3. System ddev on windows wit php 7.2

**Describe the bug**
When I try to delete a language i.e. Arabic or a currency i.e. Chinese yuan that i don't need via the backend module I get a message "item deleted successfully" however the item does not get deleted.

**To Reproduce**
1. Go to the backend module
2. Click on arrow-down -> locales -> languages
3. click on the x beside a language and say you indeed want to delete it
4. you get a success message yet the item did not get deleted

**Expected behavior**
the language should dissapear. If it is not possible to delete it for some reason it shouldn't have a delete button or at least send an error message.

**Comment by aimeos** [comment]
Our tests have shown that deleting languages/currencies works like expected in later versions. 18.4 isn't supported since July 2018 any more so you should upgrade to at least 19.10 LTS.
