### ISSUE TITLE
Admin: New Product Defaults

### ISSUE THREAD

**Issue by SirSteve** [aimeos/ai-admin-jqadm#117]
As an admin when adding a new product, I want to define default selections so that I can quickly add a new product.

For example, these are always the same: "Type: Standard" and "Language: English". There are a variety of others that are always the same as well.

**Comment by aimeos** [comment]
It's possible to define data sets that pre-select those values

**Comment by aimeos** [comment]
https://aimeos.org/tips/aimeos-2019-10-lts-release/

**Comment by aimeos** [comment]
Will be also available in 2020.07 again released in the first week of July
