### ISSUE TITLE
option delete product

### ISSUE THREAD

**Issue by ulgerman** [aimeos/ai-admin-jqadm#13]
Hey,

I've made a mistake an added an option to a product that was not suitable.
Now I want to delete it . When I click the 'x' to delete , it disappears from the screen .
When I try to save it I get this error 
An exception occurred while executing ' INSERT INTO "mshop_product" ( "typeid", "code", "label", "status", "start", "end", "config", "mtime", "editor", "target", "siteid", "ctime" ) VALUES ( 1, '0001', '32-34', 1, NULL, NULL, '[]', '2017-08-16 13:42:02', xxx@domain.com', '', 1, '2017-08-16 13:42:02' ) ': SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-0001' for key 'unq_mspro_siteid_code', /var/www/vhosts/www.domain.com/myshop/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/DB/Statement/DBAL/Simple.php:97 

When I refresh the page the option is still there.

Thanx for the follow-up.

**Comment by aimeos** [comment]
The error message says that you used the same product code already for another product. Therefore, it can't be saved.

**Comment by ulgerman** [comment]
Hey,

It's very strange . I try to change the option for the parent (selection) and the error is an error regarding a child (variant) .
I added a new parent (selection) and variants . then I added an option to the parent . when I deleted it ,it worked perfectly.

So I suppose you can close this issue.

**Comment by aimeos** [comment]
In selection products, you can create the child articles in the "Variants" sub-panel. If you've already created the articles before, it will fail if you then try to add the articles to the selection product again.

As articles are normal products in the same code namespace, you can't create child articles for selection products with codes you've already used for child articles of other selection products. Each article must have an unique SKU/EAN/invented code. This might be the case here.
