### ISSUE TITLE
Categories not visible in TYPO3 backend

### ISSUE THREAD

**Issue by marcelmarty** [aimeos/ai-admin-jqadm#134]
![category-product-view](https://user-images.githubusercontent.com/1627210/92402464-e53da200-f12f-11ea-97be-f37292cf5f17.jpg)
![category-visible](https://user-images.githubusercontent.com/1627210/92401958-08b41d00-f12f-11ea-9e9c-58a977956e18.jpg)
![category-database-view](https://user-images.githubusercontent.com/1627210/92401960-0b167700-f12f-11ea-85c9-bdb58d20b687.jpg)

**Environment**
1. Version: 20.7.2
2. Integration: TYPO3 10.4.6
3. System: XAMPP (WAMP -> Windows 10, Apache 2.4, MariaDB 10.3, PHP 7.2)

**Describe the bug**
In the Aimeos backend is just the first added category visible. All following categories are not visible in the categories section

**To Reproduce**
1. Install TYPO3 10.4.6
2. Install extension aimeos
3. Go to Aimeos backend and add a category in the categories section
4. First added category is visible, all other added categories are not visible in the categories section of the backend
5. All categories are visible when you edit a product in the backend

**Comment by aimeos** [comment]
You have created four top level categories but the Catalog panel will only show the first one.
Please make sure, you create the categories as sub-categories of your first root category by selecting the root category first before you click on the "+" symbol.

**Comment by marcelmarty** [comment]
I did try that. No luck at all. Same problem

**Comment by marcelmarty** [comment]
![category-visible-1](https://user-images.githubusercontent.com/1627210/92404642-53846380-f134-11ea-9bfc-ab6c94b6cf3a.jpg)
![category-database-view-1](https://user-images.githubusercontent.com/1627210/92404648-554e2700-f134-11ea-8b06-a27d92d06d70.jpg)
![category-product-view-1](https://user-images.githubusercontent.com/1627210/92404651-58491780-f134-11ea-8301-6d831480b625.jpg)

**Comment by aimeos** [comment]
Can you remove the category with ID 18 from the database, go to the catalog panel afterwards, click on "Root" and then on "+" to create a new sub-category of "Root"?

**Comment by marcelmarty** [comment]
Now it works... Strange...
