### ISSUE TITLE
images not uploading through admin panel

### ISSUE THREAD

**Issue by 1SA1** [aimeos/ai-admin-jqadm#135]
![1](https://user-images.githubusercontent.com/49856819/93185086-72977c80-f756-11ea-8a56-a73d3bb88cd1.png)
![2](https://user-images.githubusercontent.com/49856819/93185106-775c3080-f756-11ea-91c9-ba0d5671600f.png)

i have paste my all aimeos files on root folder except public which i have placed in cpanel public_html folder as u can see in the picture when i upload product images from admin panel it create new public folder in root directory tell me how to change its path to public_html

**Comment by aimeos** [comment]
Which integration are you using? Laravel, Symfony or TYPO3

**Comment by 1SA1** [comment]
Laravel

**Comment by aimeos** [comment]
It doesn't work to move `./public` into another folder besides the Laravel application folder. Instead, the document root must point to the `./public` folder.

**Comment by 1SA1** [comment]
u mean instead of public_html. i should use public?

**Comment by aimeos** [comment]
You can try the create a symlink for the `./public/` folder to the `../public_html/` folder
