### ISSUE TITLE
product.url is not unique after copy

### ISSUE THREAD

**Issue by guelzow** [aimeos/ai-admin-jqadm#139]
**Environment**
1. Version 2020.10.1
2. Integration TYPO3
3. System Linux

**Describe the bug**
When a product is copied, the URL segment is not unique.
And when this product is displayed in the product list, it links to the original product.

**To Reproduce**
1. Copy any product in the backend
2. Visit the product list
3. click on the newly copied product
4. See the original product

**Expected behavior**
The URL segment of the copied product should be unique

**Additional context**
Here https://github.com/aimeos/ai-admin-jqadm/blob/master/admin/jqadm/src/Admin/JQAdm/Product/Standard.php#L486
the string '_copy' is added to the `product.code` (SKU).
Adding a 
```php
$data['product.url'] = $data['product.url'] . '_' . time();
```
is our current workaround.

Tobi

**Comment by aimeos** [comment]
You are going to become the top contributor this month! :-)
Seem reasonable, can you please create a PR with the change?
