### ISSUE TITLE
coupon code stays active if all products are deleted

### ISSUE THREAD

**Issue by ulgerman** [aimeos/ai-admin-jqadm#14]
Hey,

I'm testing the shop module right now.
I've added some products to the cart and applied a coupon code 
The amount was correct.
Then I deleted all the products , but the coupon code stayed active (the total amount was negative -125)

even when I click on the shopping cart icon ( top right of site) , I see the garbage icon next to the coupon code , the code cannot be deleted

Thanx for your time
johan

**Comment by aimeos** [comment]
As this is a frontend thing, can you please open your issue here:
https://github.com/aimeos/ai-client-html

**Comment by aimeos** [comment]
Continued at https://github.com/aimeos/ai-client-html/issues/36
