### ISSUE TITLE
Datepicker is removed by Vue.js

### ISSUE THREAD

**Issue by guelzow** [aimeos/ai-admin-jqadm#141]
Hi everyone.

I'm not sure, if this is still a thing, because the JS looks a lot different in master.
But this may still apply partially.

**Environment**
1. Version 2020.7.4
2. Integration TYPO3
3. System Linux

**Describe the bug**
The UI datepicker is not being initialized, because the callback is gone.

**To Reproduce**
1. Go to the backend.
2. Click on a product.
3. Click on the start date.
4. No datepicker opening.

**Expected behavior**
The datepicker opens.

**Additional Info**
Here https://github.com/aimeos/ai-admin-jqadm/blob/2020.07.6/admin/jqadm/themes/admin.js#L1075
the date picker gets initialized. Vue.js later removes all callbacks.

**Our current workaround**
We moved the initializing method calls from the admin.js into the Vue.js `mounted` callback:

```javascript
$(function() {
	$('.vue-block').each(function() {
		var key = $(this).data('key');

		Aimeos.components[key] = new Vue({
			el: this,
			data: {data: null},
			beforeMount: function() {
				if(this.$el.dataset && this.$el.dataset.data) {
					this.data = JSON.parse(this.$el.dataset.data);
				}
			},
			methods: {
				add: function(data) {
					this.$refs[key].add(data);
				},
				remove: function(idx) {
					this.$refs[key].remove(idx);
				}
			},
			mounted: function () {
			  	this.$nextTick(function () {
					Aimeos.Config.init();
					Aimeos.Filter.init();
					Aimeos.Form.init();
					Aimeos.List.init();
					Aimeos.Log.init();
					Aimeos.Msg.init();
					Aimeos.Nav.init();
					Aimeos.Tabs.init();
			  	})
			}
		});
	});
});
```

Tobi

**Comment by aimeos** [comment]
Does this also happens in the dev-master resp 2020.10 branch because the datepicker has been replaced by flatpickr, a more sophisticated date/time picker that supports Vue.js

**Comment by guelzow** [comment]
We've just updated to master.
As far as I can tell, everything works as it should.

I'll close this one now.

Tobi
