### ISSUE TITLE
Required configuration for "controller/jobs/product/export/sitemap/location" is missing

### ISSUE THREAD

**Issue by TheWhiteShade** [aimeos/ai-admin-jqadm#144]
**Environment**
1. Version (Last)
2. Integration (Laravel)
3. System (Windows)

**Describe the bug**
While i was following  the(https://aimeos.org/docs/latest/laravel/setup/#cronjobs) i got an error with  the final cronjob command, the command is:
`0 1 * * * php /path/to/artisan aimeos:jobs "admin/cache admin/log catalog/import/csv order/cleanup/unpaid product/import/csv product/bought index/rebuild index/optimize product/export/sitemap subscription/process/begin subscription/process/renew subscription/process/end"` 
After running the command the following error appears:
![missin](https://user-images.githubusercontent.com/57576040/95938877-6d9f0a80-0da0-11eb-8f74-1d763a292663.PNG)

**Additional context**
I woul like how to solve it, though i realise that if i remove the job (product/export/sitemap) which is causing the issue the cronjob command works. I think this needs to be solvel by the right way.

**Comment by aimeos** [comment]
You have to configure the absolute directory where the sitemap file should be stored, e.g. in your ./config/shop.php
```
'controller' => [
  'jobs' => [
    'product' => [
      'export' => [
        'sitemap' => [
          'location' => public_path()
        ]
      ]
    ]
  ]
]
```
for storing it into the ./public/ directory.

**Comment by TheWhiteShade** [comment]
Thank you, it helped me!
