### ISSUE TITLE
Pay status is always authorized by default after a purchase.

### ISSUE THREAD

**Issue by TheWhiteShade** [aimeos/ai-admin-jqadm#146]
**Environment**
1. Version (e.g. 2019.10)
2. Integration (Laravel,)
3. System (Windows)

**Describe the bug**
The filed pay status 
Payment status is always set as "authorized "  automatically after the costumer make an order.

**Expected behavior**

I think the best default status for my case is "pending".

**Additional context**
How can i change from "authorized "  to "pending"?

**Comment by aimeos** [comment]
Use the "PrePay" payment service provider for "pending"
