### ISSUE TITLE
.dropdown-menu  falls under title block.

### ISSUE THREAD

**Issue by Dinver** [aimeos/ai-admin-jqadm#147]
**Environment**
1. Version (e.g. 2020.10.x-dev)
2. Integration (Laravel)
3. System (Windows)

**Describe the bug**
.btn, .dropdown-menu z-index falls under title block (.aimeos .main-navbar).

**To Reproduce**
![11](https://user-images.githubusercontent.com/36528841/97316715-1d817700-187b-11eb-96cb-c296034649f4.jpg)

**Expected behavior**
![22](https://user-images.githubusercontent.com/36528841/97316729-21ad9480-187b-11eb-9439-9af62ca63ea6.jpg)

**Additional context**
Solution 
.btn, .dropdown-menu {
    z-index: 1041;
}
or 
.aimeos .main-navbar {
    z-index: 1040;
}

**Comment by aimeos** [comment]
Thanks a lot! Can you please create a pull request with the necessary change?
```
.aimeos .main-navbar {
    z-index: 1040;
}
```

**Comment by rowild** [comment]
Since this is my short-coming, i took the liberty to provide a PR. I have currently no working 2010-installation - could someone please test before merging?
