### ISSUE TITLE
[Feature request]Allow select options for the coupon configuration

### ISSUE THREAD

**Issue by guelzow** [aimeos/ai-admin-jqadm#149]
Hi everyone.

**Is your feature request related to a problem?**
The coupon configuration allows a select as a configuration type.
The prototype of the select [here](https://github.com/aimeos/ai-admin-jqadm/blob/2ee86cc1cb497cef8e48ab7171c078a56271c614/admin/jqadm/templates/coupon/item-standard.php#L273) is empty.
The prototype gets filled [here](https://github.com/aimeos/ai-admin-jqadm/blob/2ee86cc1cb497cef8e48ab7171c078a56271c614/admin/jqadm/themes/admin.js#L340). But it does not fill the options for the select.
As a result, you end up with  an empty select.

**Describe the solution you'd like**
Define the possible options in the $beConfig of the coupon.

**Describe alternatives you've considered**
An alternative would be to scrape the select type, and allow to define custom types, the HTML code coming from a partial.

Tobi

**Comment by aimeos** [comment]
`$beConfig` is the right place and for the frontend, we use the key/value pairs in the `default` property to fill the select.
Are you able to make the changes for a prototype?

**Comment by guelzow** [comment]
> Are you able to make the changes for a prototype?
Sorry, not right now.

**Comment by aimeos** [comment]
Implemented now in https://github.com/aimeos/ai-admin-jqadm/commit/662833e1a1c2eab6f76679d82aa32c7db1f52e9c
