### ISSUE TITLE
Change prices based on different types?

### ISSUE THREAD

**Issue by parsester** [aimeos/ai-admin-jqadm#15]
i use aimeo (laravel) , i want to change price of a product when customer select another type, etc. when customer select apple iphone 7 128GB and change that to 32GB price update, or when change color from black to rosegold price change?
is that work now in aimeos?

**Comment by aimeos** [comment]
Create a product of type "Selection" and add an article for each variant. You can add different prices (and texts/images) for each of those articles and they will be shown when the customer selects another variant.

**Comment by parsester** [comment]
thanks for helping aimeos, but when i click on a selection (for example a color), the stock list was updated to new values according to selected variant, but the prices was not update,
**what should i do to change (update) the prices (cross the ajax request to api or not like the stock list with just js and css)? i want to show to customer the updated prices according to selected variant in the same page of product details before customer add the selected variant to the basket?**

**Comment by aimeos** [comment]
Your product setup is either not correct or the CSS classes in the frontend are missing to get the desired change. We've added an example in the Aimeos demo data now. The price of the first selection variant is slightly lower than that of the selection product itself and you will see it if you select the attributes blue/34/32 (color/length/width). To test it yourself, set up a new Aimeos installation (use "aimeos/aimeos-laravel": "dev-master") and follow the setup guide.

**Comment by parsester** [comment]
i use aimeos-laravel: 2017.7
i check online demo example which you mentioned, but it was not what i said, the price does not change on the same page (of course when i select attributes blue/34/32) stock-list was changed in same page and only when i click on Add to basket button, in the Basket modal that appears price has been changed and displayed...
i want to when customer click select attributes blue/34/32 the price the price of the above line is written change to selected variant...
technically, i need, when customer select attributes blue/34/32 or another attributes, which is actually a kind of that product preferably show loading and as a ajax request get new price-list block and replaced by the previous price list, or not in another form get price-list of all variants of the selection type product when page is loading, show a default price and hide another price-lists and when customer select attributes based on choice, hide current price-list and show price-list of that choice...
if you want to see an example, this is done on the Amazon website in [this link](https://www.amazon.com/dp/B01LWCRA3R/ref=twister_B073QMF6Z9?_encoding=UTF8&th=1) for example.

is my request already implemented in aimeos laravel?
with what AJAX request, can I get prices for a product or a variant of product in json response?
how can i create an AJAX request to get a list of prices for a product or a variant of product that get a html content of price-item in response?

**Comment by nos3** [comment]
I can remember that there was a problem with this feature in 2017.07 because you are right, in the demo setups it doesn't currently work. It has been fixed in the dev-master branch but maybe not backported to 2017.07. If you wait until tomorrow, the new version 2017.10 will be out that contains the working feature. In the meantime, you can also use the dev-master branch as suggested.

**Comment by parsester** [comment]
thanks for your commented **nos3**
i wait for new version 2017.10, but i implement my own extension instead of ai-client-html
i want to know how i can upgrade to the new version while my changes do not go away and as well as all new features & changes in this version also apply?

**Comment by aimeos** [comment]
Your project specific templates and classes must be in an own extension:
- https://aimeos.org/docs/Laravel/Extend_Aimeos
- https://aimeos.org/docs/Developers/Create_an_extension

**Comment by parsester** [comment]
thanks for your commented nos3
i check version 2017.10 for aimeos/ai-admin-jqadm has already been released?are you mean new version 2017.10 for aimeos/aimeos-laravel to be released?
i wait for new version 2017.10, but i implement my own extension instead of ai-client-html
i want to know how i can upgrade to the new version while my changes do not go away and as well as all new features & changes in this version also apply?
