### ISSUE TITLE
js bug create/update pages in admin panel (uncritical).

### ISSUE THREAD

**Issue by Dinver** [aimeos/ai-admin-jqadm#150]
**Environment**
1. Version (2020.10.x-dev)
2. Integration (Laravel)
3. System (Windows 10)

**Describe the bug**
On all pages (create/update) in admin panel:
![error](https://user-images.githubusercontent.com/36528841/97540054-1b7efb80-19d4-11eb-8030-bd376a545ecb.jpg)

**To Reproduce**
Simply install 2020.10.x-dev

**Comment by aimeos** [comment]
Thanks, we noticed that too. Meanwhile, the fix is in 2020.10.x-dev

**Comment by Dinver** [comment]
> Thanks, we noticed that too. Meanwhile, the fix is in 2020.10.x-dev

"aimeos/ai-client-html": "2020.10.x-dev"
"aimeos/aimeos-laravel": "2020.10.x-dev"

Updated today, error there is

**Comment by aimeos** [comment]
The fix was committed very recently so please try again. You need commit https://github.com/aimeos/ai-admin-jqadm/commit/1a87fe44907fcad6fddf5940b188b9647ea735cd

**Comment by Dinver** [comment]
> The fix was committed very recently so please try again. You need commit [1a87fe4](https://github.com/aimeos/ai-admin-jqadm/commit/1a87fe44907fcad6fddf5940b188b9647ea735cd)

Thanks, it working.
