### ISSUE TITLE
Product list -> reset search not working

### ISSUE THREAD

**Issue by rowild** [aimeos/ai-admin-jqadm#154]
**Environment**
1. Version (e.g. 2020.10)
2. Integration (TYPO3)
3. System (Mac)

**Describe the bug**

The "reset search" button doesn't do anything.

![aimes-admin-reset-search](https://user-images.githubusercontent.com/213803/99187224-988ccd80-2755-11eb-9c99-ebb302ac8bbc.png)

**Expected behavior**
The reset-search button should clear all input and reset all select fields.

**Comment by aimeos** [comment]
Thank you for your bug report. We can confirm the issue and care about it. We update the issue as soon as it's done.

**Comment by aimeos** [comment]
The problems has been fix by this commit and will be part of the next minor release: https://github.com/aimeos/ai-admin-jqadm/commit/39f2c2a4ba13ce76e08e069e079fba3966aca445

**Comment by rowild** [comment]
Nice! Thank you!
