### ISSUE TITLE
Mixed content issue on categories page

### ISSUE THREAD

**Issue by wing5wong** [aimeos/ai-admin-jqadm#155]
**Environment**
1. Version (e.g. 2017.10)
Installing aimeos/aimeos (2020.10.3)

2. Integration (Laravel, TYPO3, Symfony, SlimPHP or Flow)
Laravel

3. System (Linux, Mac, Windows)
Windows

**Describe the bug**
Mixed content warning and not possible to edit categories on fresh install
```VM489:1 Mixed Content: The page at 'https://X/admin/default/jqadm/search/catalog?lang=en' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://X/admin/default/jsonadm'. This request has been blocked; the content must be served over HTTPS.```

Categories can be created but then can not be edited as they are not displayed in the list
![image](https://user-images.githubusercontent.com/4406993/99643272-5a730f00-2ab1-11eb-9f32-e04b72bf852f.png)

**To Reproduce**
- composer create-project aimeos/aimeos shop
- Visit admin page
- Visit Categories
- Error in console.

**Expected behavior**
No mixed content warning and categories displayed.

**Additional context**
Seemed to have this problem with earlier version too, so wondering if somehow related to my specific configuration... not sure how or if its true though

**Comment by aimeos** [comment]
Can you check the APP_URL setting in your .env file if its value starts with "https://"?

**Comment by wing5wong** [comment]
Hi, yes the issue persists with the configuration here
![image](https://user-images.githubusercontent.com/4406993/99760860-9c579000-2b59-11eb-8249-f621a8e559d2.png)

after checking this i ran
`php artisan config:cache`

**Comment by wing5wong** [comment]
Sorry i have resolved this - it appears using cloudflare and flexible ssl results in connection to http vhosts here rather than ssl
Im not sure if the generated url can be changed or not to work with this setup, but configuring full rather than flexible results in expected behaviour
![image](https://user-images.githubusercontent.com/4406993/99762304-0f163a80-2b5d-11eb-9ac2-81f533ad55b4.png)
