### ISSUE TITLE
Add Option/Value button not working

### ISSUE THREAD

**Issue by rowild** [aimeos/ai-admin-jqadm#157]
**Environment**
1. Version (e.g. 2020.10.3)
2. Integration (Laravel, TYPO3, Symfony, SlimPHP or Flow)
3. System (Linux, Mac, Windows)

**Describe the bug**
When assigning a product to a category/supplier/customer, the "add options/value" button does not work. 

![Aimeos-assign-option-value-btn-not-working](https://user-images.githubusercontent.com/213803/99702391-fee75800-2a95-11eb-8751-362df2c4548e.jpg)

**Comment by aimeos** [comment]
Thank you for your bug report. We will see how we can fix it.

**Comment by aimeos** [comment]
The panel has been completely rewritten in dev-master as Vue.js component.
In 2020.10 LTS, the option/value table has been removed because it's not used and was hardly possible to fix with Vue.js and jQuery mixed.
