### ISSUE TITLE
After update, request to update

### ISSUE THREAD

**Issue by Dinver** [aimeos/ai-admin-jqadm#158]
**Environment**
1. 
composer.json  
"aimeos/ai-client-html": "2020.10.x-dev",
"aimeos/aimeos-laravel": "2020.10.x-dev",
"aimeos/map": "~1.8"

in composer.lock
"aimeos/ai-admin-jqadm": "2020.10.6"
2. Laravel
3. Windows

**Describe the bug**
After today's update in admin panel there was an error "Update", with link [https://aimeos.org/update/?type=Laravel&version=2020.10.x-dev](url)

**To Reproduce**
1. composer update

**Expected behavior**
nothing

**Screenshots**
![image](https://user-images.githubusercontent.com/36528841/100065145-7f1a0e80-2e44-11eb-9ad3-4f244757b495.png)

What needs to be updated?

**Comment by aimeos** [comment]
This is due to using the -dev version. If you switch back to "~2020.10", the latest version is recognized.

**Comment by Dinver** [comment]
> This is due to using the -dev version. If you switch back to "~2020.10", the latest version is recognized.

can this be disabled?

**Comment by aimeos** [comment]
Not by configuration, because it's important to inform about for security updates
