### ISSUE TITLE
Edit review page

### ISSUE THREAD

**Issue by Dinver** [aimeos/ai-admin-jqadm#159]
**Environment**
1. 2020.10.x-dev
2.Laravel
3. Windows 10

**Screenshots**
![review](https://user-images.githubusercontent.com/36528841/100077686-b47a2880-2e53-11eb-9a16-9e3f1f232f35.jpg)

\ext\ai-admin-jqadm\admin\jqadm\templates\review\item-standard.php
26 < div >
27 < /div >

line 188 excess < /div >

**Comment by aimeos** [comment]
Can you please create a pull request with the fix?

**Comment by Dinver** [comment]
> Can you please create a pull request with the fix?

Created

**Comment by aimeos** [comment]
Great and thank you very much!
