### ISSUE TITLE
List paging dissapears / wrong paging limits

### ISSUE THREAD

**Issue by jgerhold** [aimeos/ai-admin-jqadm#16]
- If you have a list (like the products) which has more than one page
- and you select a limit that is greater than the max item count
=> the paging elements disappear.

**Additionally the list will only display the items starting from the page you were on before.**

The paging settings seen to be saved in the session.
So you have to logout and log back in to reset the paging.

Browser: Chrome/Mac

**Comment by jgerhold** [comment]
- Perhaps the paging should never be hidden.
- I did not find the place where it is best to make a paging parameter sanity check to change the paging start when all items can be displayed.
- Additionally I would make the paging dropdown click targets bigger:
```
ai-admin-jqadm/admin/jqadm/themes/default/nav.css:

.aimeos .list-page .dropdown-item {
  padding: 0;
}

.aimeos .list-page .dropdown-item a {
  display: block;
  padding: 3px 1.5rem;
}
```

**Comment by aimeos** [comment]
Thank you for your bug report! This commit fixes the problem: https://github.com/aimeos/ai-admin-jqadm/commit/6bbc5e3f08773fc6f647b26e3dd715cdb547de19

It always displays the bottom pagination and adds your CSS. Maybe you can create a PR in the Bootstrap repo for your CSS changes so everybody will profit.

**Comment by jgerhold** [comment]
The paging is now visible, but the list still does not start at the first item when the page limit > total items when I switched to a second page before changing the page limit.

**Comment by aimeos** [comment]
We are not sure if we should reset the the page to the first item when the user only changes the page limit. From the usability point of view this might be contra productive but maybe users expects this ...

**Comment by jgerhold** [comment]
I would expect it if total items > page limit.

**Comment by aimeos** [comment]
OK, thanks
