### ISSUE TITLE
Settings display of columns not working and not save

### ISSUE THREAD

**Issue by Dinver** [aimeos/ai-admin-jqadm#161]
Environment
1. 2020.10.x-dev/ admin.demo.aimeos.org
2. Laravel
3. Windows 10

**Screenshots**
![demo](https://user-images.githubusercontent.com/36528841/102185994-fe8a8300-3ec2-11eb-9390-9cf5b1e08ffa.gif)

**Comment by aimeos** [comment]
You have to click on the magnifier icon to reload the list
