### ISSUE TITLE
"Error saving data"

### ISSUE THREAD

**Issue by neolium** [aimeos/ai-admin-jqadm#165]
**Environment**
1. Version (**_2020.10.6_**)
2. Integration (**_Laravel_**, TYPO3, Symfony, SlimPHP or Flow)
3. System (**_Linux_**, Mac, Windows)

**Describe the bug**
Cant edit or create a product - always same error, no logs at all

**To Reproduce**
1) Open demoproduct, change price, click save - error happens
**Expected behavior**
Save the changes? :D

**Screenshots**
https://i.imgur.com/fDImHiF.png

**Additional context**

**Comment by aimeos** [comment]
Please have a look into the Log panel (extended left navigation) to see which error occured

**Comment by neolium** [comment]
As described - all logs are empty. On the logfile u said are only errors about the permissions for the storage-folder. I chmod'ed them to recursive 777... php-log is empty, laravel-log-folder is empty...

**Comment by neolium** [comment]
I just set the complete shopfolder to recursive 777 and now it works...
(Its just for development purposes, when i deploy the site and get the error again i will reopen the issue).
