### ISSUE TITLE
Categories not showing up

### ISSUE THREAD

**Issue by exzaadmin** [aimeos/ai-admin-jqadm#167]
I am adding the product categories. But they are not showing up in the front end. How to solve this problem?

**Comment by rowild** [comment]
In my experience, that plugin only defines from which categories the products are collected. I had to use the filter plugin to display a category tree or any other kind of category layout.
Come over to Slack - there is better help! Github is just for error reporting.

**Comment by aimeos** [comment]
For questions regarding how to do something, the Aimeos forum is much better suited: https://aimeos.org/help
The Github issue tracker is only for bug reports or feature requests.
