### ISSUE TITLE
Order Service Attribute

### ISSUE THREAD

**Issue by exemplari** [aimeos/ai-admin-jqadm#168]
**Environment**
"aimeos/aimeos-laravel": "~2020.10"

**Describe the bug**
order.base.service.attribute not saving

**To Reproduce**
1. got to an order /admin/jqadm/get/order/9?lang=en
2. Add an attribute to the delivery service
3. Save

**Expected behavior**
The attribute should be attached to the delivery. Like trackingid. 

**Screenshots**
![Capture1](https://user-images.githubusercontent.com/541161/104667626-5287b380-568b-11eb-9fbc-04bc8538a93d.JPG)

**Additional context**
How i solved this. There seemed to be multiple problems
customer controller . Aimeos\Admin\JQAdm\Order\Mycontroller
Aimeos\Admin\JQAdm\Order\Standard
Line 452 - this basket list is not indexed by serviceid
foreach( $services as $serviceId => $service )
			{
				$list = [];
				$attrItems = $service->getAttributeItems();

				if( isset( $data['service'][$type][$serviceId] ) )

----
foreach( $services as $idx => $service )
			{
				$serviceId = $service->getServiceId();
				$list = [];
				$attrItems = $service->getAttributeItems();

				if( isset( $data['service'][$type][$serviceId] ) )

Line 476 - patched in the name as required, possibly frontend issue
+$array['order.base.service.attribute.name'] = $array['order.base.service.attribute.code'];

Line 478 - this was erroring
$attrItem->fromArray( $array, true );
----
$attrItem->fromArray( $array, false );

**Comment by aimeos** [comment]
Thank you for your bug report. Can you create a PR fixing the issue?

**Comment by exemplari** [comment]
Just went over your docs for submitting PR. I will setup the environment to use in the future but it will be a few days before so whomever gets the fix first is fine.

**Comment by aimeos** [comment]
Fixed with https://github.com/aimeos/ai-admin-jqadm/commit/63526c83b16c5500adb86512adfa1ed2fcb4e19d#diff-cd97927cc6cfc6ababfd60a454a25b8acf917f7b031d6252da33cd2286630ccc
