### ISSUE TITLE
[Feature request] As a product editor, I only want to use the attribute types that are active.

### ISSUE THREAD

**Issue by guelzow** [aimeos/ai-admin-jqadm#171]
Hi everyone.

**Is your feature request related to a problem?**
When editing products, the dropdown from _options/configurable_ and _options/type_ supplies the complete list of attribute types. Even the disabled ones are shown.

**Describe the solution you'd like**
Apply a filter here:
https://github.com/aimeos/ai-admin-jqadm/blob/2020.10.14/admin/jqadm/themes/product.js#L268
```js
var criteria = {'>': {'attribute.type.status': 0}};
Aimeos.getOptions(request, response, element, 'attribute/type', 'attribute.type.code', 'attribute.type.code', criteria);
```
That will display only the active types.

**Describe alternatives you've considered**
An alternative would be to declare a new mixin method, because the change above might be considered a breaking change.
This new method then must be used here
https://github.com/aimeos/ai-admin-jqadm/blob/2020.10.14/admin/jqadm/templates/product/item-option-config-standard.php#L69
and here
https://github.com/aimeos/ai-admin-jqadm/blob/2020.10.14/admin/jqadm/templates/product/item-option-custom-standard.php#L67

**Additional context**
Screenshot of a filtered list
![grafik](https://user-images.githubusercontent.com/11192910/105733055-635ce280-5f31-11eb-9757-af21ff8c328a.png)

Tobi

**Comment by aimeos** [comment]
Adding an additional criteria is OK and we don't consider this as breaking change (no interfaces or signatures changed).
Can you create a PR for the required change?

**Comment by guelzow** [comment]
> Can you create a PR for the required change?
Done.

**Comment by aimeos** [comment]
PR is merged. Thanks again!
