### ISSUE TITLE
debug bar causes error on save issue

### ISSUE THREAD

**Issue by akropivko** [aimeos/ai-admin-jqadm#174]
**Environment**
1. Version 2020.10.06
2. Integration Laravel
3. System  Windows

**Describe the bug**
Frequently used Laravel Debugbar package causes error on save issue - see https://aimeos.org/help/laravel-package-f18/error-on-save-after-clicking-on-characteristics-without-adding-one-t3394.html for detail

**To Reproduce**
1. Install Laravel Debugbar package from https://github.com/barryvdh/laravel-debugbar 
2. Open product in edit mode, go to Media tab.
3. Click twice on Save button
4. See error - https://aimeos.org/help/download/file.php?id=797

It's famous frequently used package. Would be good to be able to use it.

**Comment by aimeos** [comment]
Do you have any clue what happens and why this happen when the Laravel Debugbar package is installed? This would help a lot to fix the problem.

**Comment by akropivko** [comment]
In case of using Clockwork debug tool there is no problem- https://prnt.sc/xr2doi 
As you can see the Clockwork panel is available as an additional tab of chrome debug tools.
Since the Laravel Debugbar is available as an additional frontend element, I think this is the cause of the problem - https://prnt.sc/xr2vdm

**Comment by aimeos** [comment]
Merge in dev-master and 2020.10.x-dev, will be part of the next release.
Thank you very much for your help!
