### ISSUE TITLE
Clicking on + icon to add the variant cause block collapsing

### ISSUE THREAD

**Issue by akropivko** [aimeos/ai-admin-jqadm#176]
**Environment**
1. Version 2020.10.6
2. Integration Laravel
3. System Windows

**Describe the bug**
Clicking on + icon to add the variant cause block collapsing - https://prnt.sc/yjds0q 
Result after clicking the + - https://prnt.sc/yje1wy
Opened - https://prnt.sc/yje4ce Ok, added. But why collapsing before?

**To Reproduce**
1. Create a selection product
2. Try to add a new variant as shown on sreenshots above

**Comment by aimeos** [comment]
Thanks for reporting.
This is not the case any more in dev-master and we will try to backport the changes to 2020.10 too.

**Comment by akropivko** [comment]
thanks!

**Comment by aimeos** [comment]
New version 2020.10.16 with the fix has been released
