### ISSUE TITLE
ErrorError saving data if selection product variant was added manually 

### ISSUE THREAD

**Issue by akropivko** [aimeos/ai-admin-jqadm#177]
**Environment**
1. Version 2020.10.6
2. Integration Laravel
3. System Windows

**Describe the bug**
ErrorError saving data if selection product variant was added manually  - https://prnt.sc/yjephg No way to skip the error except reopen the product in edit mode again.
But if no variant before clicking the Save btn, then everything is OK - https://prnt.sc/yjf1xn , next screenshot: the item was saved and the variant attr was added automatically - https://prnt.sc/yjf7pf 

**To Reproduce**
1. Create a selection product
2. Try to add a new variant and set variant attribute manually

**Expected behavior**
Do not show the error.

**Additional context**

**Comment by aimeos** [comment]
Seems like you add an existing article to the selection product which already has the variant attributes attached. Then, adding the same variant attribute again causes a duplicate entry error for the variant attribute.
If you add an existing article to a selection product, save the product without adding variant articles. They will then show up after saving the product.

**Comment by akropivko** [comment]
Thanks for response. Another problem is when a user has the "ErrorError saving data" he/she just can't fix the error in the same editing session. Having this error you should to cancel editing and then start all thing from scratch, loosing all the data entered before.

**Comment by aimeos** [comment]
Released a new version of aimeos/ai-admin-jqadm (2020.10.16) which adds the variant attributes immediately after selecting the article to the right panel. Thus, the problem of users adding variant attributes twice can't happen any more.
