### ISSUE TITLE
"error saving data" and "Integrity constraint violation" annoyed issue

### ISSUE THREAD

**Issue by akropivko** [aimeos/ai-admin-jqadm#178]
**Environment**
1. Version 2020.10.6
2. Integration Laravel
3. System Windows

**Describe the bug**
Guys, could you please do something with this really really annoyed "error saving data" and "Integrity constraint violation" issues?? See attached screenshots
![Screenshot_22](https://user-images.githubusercontent.com/66216139/107195305-db2f1080-69f9-11eb-9eb7-ce7573436568.jpg)
![Screenshot_21](https://user-images.githubusercontent.com/66216139/107195308-dc603d80-69f9-11eb-917b-d1c92b7669ef.jpg)

I do not do neither something special nor something unusual within admin interface. Just duplicate a product, edit its setting in very usual way for shop admin interface. I did the same things thousands times in other shop's admin interfaces.  It's really bad when you do something usual for several minutes and then... ta-tam - "error saving data" and NO WAY to resolve it except to do all the same from scratch. 

**To Reproduce**
1. Just usual routine in admin interface.

**Expected behavior**
Just usual routine in admin interface without strange errors.

**Comment by aimeos** [comment]
Seems like you copy the same product again and again but don't ever change the SKU. This leads to most of your foreign key constraint issues.

In future version we want to include a check specific for duplicate SKUs.

**Comment by akropivko** [comment]
Thanks for quick response. 
I see, but in this case a user need an ability to resolve the issue without loosing ALL the data he/she entered before. I assume I need just to edit the SKU of the products or SKUs of its selections and then just save my data. But for some reason I need to cancel the editing mode and then try to do all the same from scratch! This is the really problematic.

**Comment by aimeos** [comment]
SKU and code field values of copied items now get a random value appended. This will prevent the described problems if you don't change the value yourself.

**Comment by akropivko** [comment]
thanks!

**Comment by akropivko** [comment]
Sorry, but seems it's not solve the problem. I've updated the package and now when I copy a selection product I can see the random value appended to SKU  - see attach
![Screenshot_23](https://user-images.githubusercontent.com/66216139/107851930-0361a980-6e16-11eb-8136-7c1213fac3ea.jpg)

But when I click the Save btn I have totally the same problem - 
![Screenshot_24](https://user-images.githubusercontent.com/66216139/107851953-36a43880-6e16-11eb-9a59-6daa760b34a9.jpg)

Ok, I already know this is because of same selection items SKU - 
![Screenshot_25](https://user-images.githubusercontent.com/66216139/107851974-5c314200-6e16-11eb-9dd2-73d8980e90a4.jpg)

Ok, let's assume that's my fault. So let me just delete all the selection items, add a new one with new SKU and then click the Save btn again - the same problem
![Screenshot_26](https://user-images.githubusercontent.com/66216139/107852021-c34ef680-6e16-11eb-88fd-a5526e210e9b.jpg)

So I need to exit from edit mode loosing all the date and then try again from scratch. You see the problem?  The solution would be to make it possible to correct the problem manually in the same editing session without exiting the edit mode. This is what usually expected in such case.

**Comment by aimeos** [comment]
Copying a selection product and saving it without any changes works now too if you update by executing:
```
composer req aimeos/ai-admin-jqadm:2020.10.x-dev
```
It don't make sense in real world but prevents the error without knowing where the problem is. If you add a new item and use a variant article SKU that already exists, you will still get the error but that has to be fixed in 2021.x because it's a bigger task. There's also an issue ticket for that: #114

**Comment by akropivko** [comment]
I see. Thank you!
