### ISSUE TITLE
Subcategory is not displayed in default view

### ISSUE THREAD

**Issue by sebkln** [aimeos/ai-admin-jqadm#18]
Hi, I'm testing the aimeos TYPO3 web shop distribution. When I add new subcategories in the default admin interface, this new categories exist, but aren't shown in the list.

After saving a subcategory, an 'arrow-right' symbol is shown left to the parent category. This arrow disappears when I click on it. Nothing else happens.

````
▼ Home
    Category A
  ► Category B
      Subcategory (never shown)
````

In the expert mode I'm able to see and rearrange all categories.

TYPO3: 8.7.8 (non-composer mode)
aimeos: 17.10.0
aimeos_dist: 17.10.0
PHP: 7.0.22

Tested in Chrome (61.0.3163.100) and Firefox (56.0.2).

Sidenote: In Firefox the 'arrow-down' symbol of the category list is shown, but the 'arrow-right' symbol is missing and replaced by the 'question mark box' symbol (replacement character).

**Comment by aimeos** [comment]
Thank you for your bug report! We've found the problem: https://github.com/aimeos/ai-admin-jqadm/commit/0c718e6ddaadeb9ae8b927ffc9f12675594da26d
It will be part of the next release of the Aimeos TYPO3 extension in the TER
