### ISSUE TITLE
new translation file

### ISSUE THREAD

**Issue by akropivko** [aimeos/ai-admin-jqadm#180]
I can't upload a new translation file for some reason, see attach.
![Screenshot_35](https://user-images.githubusercontent.com/66216139/109393007-1e5d0f00-7928-11eb-9743-ea8f12985c83.jpg)

Please use for vendor/aimeos/aimeos-core/i18n/country/uk.po  - https://drive.google.com/file/d/1WVDRoXI5atANE4XT2PlGQoAiidfbb06-/view?usp=sharing

**Comment by aimeos** [comment]
I was able to upload the file after copying the content to a new file. Please make sure the file is encoded as UTF-8.
