### ISSUE TITLE
billing/disable-new and delivery/disable-new configuration options still old

### ISSUE THREAD

**Issue by akropivko** [aimeos/ai-admin-jqadm#181]
**Environment**
1. Version 2020.10.6
2. Integration Laravel
3. System Windows

**Describe the bug**
Two config options billing/disable-new and delivery/disable-new still use old (deprecated) settings - see screens below.
![Screenshot_37](https://user-images.githubusercontent.com/66216139/109475678-a9e8b400-7a7e-11eb-8854-bbf805b4cacd.jpg)

![Screenshot_38](https://user-images.githubusercontent.com/66216139/109475848-dd2b4300-7a7e-11eb-8ff9-c2a83e00c5a0.jpg)

**Comment by aimeos** [comment]
You are right, the templates used the old settings while the class used the new ones.
This has been fixed in dev-master and 2020.10.x-dev now.

Can you please test yourself by executing:
`composer req aimeos/ai-client-html:2020.10.x.dev`

BTW: The correct values is `1` or `true`, not `[1]`
