### ISSUE TITLE
Admin area In Types -> Prices Position column is missing

### ISSUE THREAD

**Issue by oulfr** [aimeos/ai-admin-jqadm#185]
In admin area -> Types->Prices ther is a missing position field in columns and there is a duplicate price domain.

in price/list-standard.php : 

- 'price.type.position' => ['op' => '>=', 'type' => 'number'] is missing 
-    'price' => $this->translate('admin', 'price'), is duplicated

`<?= $this->partial(
                                $this->config('admin/jqadm/partial/listsearch', 'common/partials/listsearch-standard'), [
                                'fields' => array_merge($fields, ['select']), 'filter' => $this->session('aimeos/admin/jqadm/type/price/filter', []),
                                'data' => [
                                    'price.type.id' => ['op' => '=='],
                                    'price.type.domain' => ['op' => '==', 'type' => 'select', 'val' => [
                                        'price' => $this->translate('admin', 'price'),
                                        'catalog' => $this->translate('admin', 'catalog'),
                                        'customer' => $this->translate('admin', 'customer'),
                                        'media' => $this->translate('admin', 'media'),
                                        'product' => $this->translate('admin', 'product'),
                                        'service' => $this->translate('admin', 'service'),
                                        'supplier' => $this->translate('admin', 'supplier'),
                                        'text' => $this->translate('admin', 'text'),
                                    ]],
                                    'price.type.status' => ['op' => '==', 'type' => 'select', 'val' => [
                                        '1' => $this->translate('mshop/code', 'status:1'),
                                        '0' => $this->translate('mshop/code', 'status:0'),
                                        '-1' => $this->translate('mshop/code', 'status:-1'),
                                        '-2' => $this->translate('mshop/code', 'status:-2'),
                                    ]],
                                    'price.type.code' => [],
                                    'price.type.label' => [],
                                    'price.type.position' => ['op' => '>=', 'type' => 'number'],
                                    'price.type.ctime' => ['op' => '-', 'type' => 'datetime-local'],
                                    'price.type.mtime' => ['op' => '-', 'type' => 'datetime-local'],
                                    'price.type.editor' => [],
                                ]
                            ]);
                            ?>`

**Comment by aimeos** [comment]
Thank you for your bug report!
Can you create a PR with a fix for the problem?

**Comment by oulfr** [comment]
Yeh of course, this is the PR: [https://github.com/aimeos/ai-admin-jqadm/pull/186](url)
