### ISSUE TITLE
Order By columns in Order details not working 

### ISSUE THREAD

**Issue by oulfr** [aimeos/ai-admin-jqadm#187]
From invoice tab in order detail the order by columns not working

**Comment by aimeos** [comment]
There's only one invoice row, so sorting doesn't make sense. We are planning to change that to a card instead of a table in one of the next releases.

**Comment by oulfr** [comment]
what reported here is not just the order of columns but also the detail page also is losed after click in sort of column, do you have a date of the next realeases ?

**Comment by oulfr** [comment]
The issue concern not only order detail page but the customer page also and i think all detail page that contains a table

**Comment by aimeos** [comment]
Yes, you are right. This seems to be a problem of all sub-panels with data tables.
We will check how we can fix that.

**Comment by aimeos** [comment]
The problem has been fixed by commit https://github.com/aimeos/ai-admin-jqadm/commit/622ff40041cf338bf948d79d6c2b85fa164dc236. You can test yourself by executing on the CLI:
```
composer req aimeos/ai-admin-jqadm:2020.10.x-dev
```
