### ISSUE TITLE
Admin default menu performance issue

### ISSUE THREAD

**Issue by oulfr** [aimeos/ai-admin-jqadm#188]
When we have many sites more than 1000 the default menu in admin area take hug of time to show because a lot of data.It's better to paginate this menu or add searchable list

**Comment by aimeos** [comment]
The sites menu has been rewritten in the new 2021.04 version released today. Now it works with an arbitrary amount of sites without problems

**Comment by oulfr** [comment]
how we can update all package to this last version ?

**Comment by aimeos** [comment]
https://aimeos.org/docs/latest/laravel/setup/#upgrade

**Comment by aimeos** [comment]
"aimeos/aimeos-laravel": "~2021.04"
https://github.com/aimeos/aimeos-laravel#installation
