### ISSUE TITLE
All options - value not working

### ISSUE THREAD

**Issue by oulfr** [aimeos/ai-admin-jqadm#189]
**ai-admin-jqadm version 2021.04**

All options value in list not saved and still empty.
for example supplier->edit->Texts->Advanced-> add options and value then save.
after save the options value is empty

**Comment by aimeos** [comment]
Thank you very much for you bug report. The problem has been fixed with this commit: https://github.com/aimeos/ai-admin-jqadm/commit/ef8d3b22590cb81569a344ca5e816983cf428372

You can test yourself if you install `aimeos/ai-admin-jqadm:2021.04.x-dev`:
```
composer req aimeos/ai-admin-jqadm:2021.04.x-dev
```
