### ISSUE TITLE
How to  returned OR refused product from customer side ?

### ISSUE THREAD

**Issue by yashIndianic** [aimeos/ai-admin-jqadm#190]
How to  returned OR refused product from customer side ?

- Once customer product purchase and there is no option for product returned OR refused.

**Comment by aimeos** [comment]
In the order detail panel, you can select for each order if it's returned or refused

**Comment by yashIndianic** [comment]
yes you right but not available in customer side

**Comment by aimeos** [comment]
Do you mean in the customer profile (frontend)? Then no, customers shouldn't be able to change that status. It's for the shop owner only.

**Comment by yashIndianic** [comment]
Ok . Thanks

**Comment by aimeos** [comment]
However, you can change that easily in your own templates, if you feel it's useful for your use case.
