### ISSUE TITLE
Variant's product.timeframe gets overwritten when edited via "Selection"->Variants

### ISSUE THREAD

**Issue by jonaseberle** [aimeos/ai-admin-jqadm#192]
**Environment**
1. Version
2020.10
2. Integration (Laravel, TYPO3, Symfony, SlimPHP or Flow)
TYPO3
3. System (Linux, Mac, Windows)
Linux

**Describe the bug**
If a product that is used as a variant in a "Selection" product has a timeframe ("Delivery within") set in a stock record it will be removed if the stock level is updated from the "Selection product"

**To Reproduce**
1. Go to variant product
2. Click on Stocks
3. Add a stock entry ("Stock Level"=empty, "Delivery within"=666 days)
4. Go to main product
5. click on "Variants"
6. edit the stock level of the variant
7. Go back to variant product
8. Click on Stocks
8. See "Delivery within" is missing

**Expected behavior**
"Delivery within" is not emptied.
The best solution would be to also include "Delivery Within" in the main product -> variants interface. This would allow editors to have the same convenience of not having to open the variant for "Delivery Within" as when editing stock levels.

**Screenshots**
Main ("Selection") product -> Variants:
<img width="709" alt="image" src="https://user-images.githubusercontent.com/1678001/119117439-830c9f00-ba29-11eb-9835-7d90d974738d.png">

Variant -> Stocks:
<img width="881" alt="image" src="https://user-images.githubusercontent.com/1678001/119117527-99b2f600-ba29-11eb-8fec-b49753326f7a.png">

**Additional context**
I haven't checked if this is already fixed in master.

**Comment by aimeos** [comment]
Problem has been fixed in 2020.10.x-dev. The 2021.04 and dev-master branches were not affected.
