### ISSUE TITLE
Users section is not working on laravel backend demo

### ISSUE THREAD

**Issue by tusharag432** [aimeos/ai-admin-jqadm#196]
**Environment**
1. Version 2021.04.4
2. Integration Laravel
3. System (Windows)

**Describe the bug**
https://admin.demo.aimeos.org/admin/default/jqadm/search/dashboard?locale=en On this page, if I try to click on users, the sidebar will open but it won't show users on the main screen

**To Reproduce**
1. Go to 'https://admin.demo.aimeos.org/admin/default/jqadm/search/dashboard?locale=en'
2. Click on 'users'
3. Scroll down to ''

**Expected behavior**
It should have shown a list of users but it shows the previous page I was on

**Screenshots**
![image](https://user-images.githubusercontent.com/86533370/125746988-5e3ffabc-92df-4ce0-8401-11b88da10736.png)

**Additional context**
No

**Comment by aimeos** [comment]
The customer panel is disabled in the demo to avoid people changing the password of the users.
