### ISSUE TITLE
Property-table v-bind:i18n does not work with translates where ` symbol exists.

### ISSUE THREAD

**Issue by zherdev-artem** [aimeos/ai-admin-jqadm#197]
Hi

**Environment**
1. Version (e.g. aimeos/ai-admin-jqadm:2021.04.12)
2. Integration (Laravel)
3. System (Mac)

**Describe the bug**
In Ukrainian language property-table translation has symbol, like "Property value (required)" => "Значення властивості (обов`язково)"

All of the property-standard admin templates have ` in v-bind:i18n object:
![image](https://user-images.githubusercontent.com/4329958/126066913-a0e942e5-3649-4cff-9176-8fb208d25d38.png)

Due to this vue do not render component as expected. The fix is to paste ' instead ` or somehow escaping symbols in the object.
![image](https://user-images.githubusercontent.com/4329958/126066985-6b2594fd-d3d3-4b74-a902-3600e1b10956.png)

Please, fix it everywhere.

**Comment by aimeos** [comment]
Thanks for the hint. The escape problem is now fixed in `dev-master` and `2021.07.x-dev`
