### ISSUE TITLE
Missing countries options in selection

### ISSUE THREAD

**Issue by switch-cheehau** [aimeos/ai-admin-jqadm#198]
Hi Aimeos,

Please check this line:
https://github.com/aimeos/ai-admin-jqadm/blob/725e496417eb42e401ad79d63f4380ec8f41da9e/admin/jqadm/src/Admin/JQAdm/Order/Standard.php#L37

![image](https://user-images.githubusercontent.com/82187386/126283529-8020bb57-c4ea-44be-bc1f-5374e10781d7.png)

It fixed if i change to 
```
 foreach( $this->getContext()->config()->get( 'common/countries', [] ) as $code ) { 
```

**Comment by aimeos** [comment]
Thanks, has been fixed now
