### ISSUE TITLE
How to create bulk products using csv?

### ISSUE THREAD

**Issue by srigovind30** [aimeos/ai-admin-jqadm#20]
In Aimeos admin is there any option to upload product csv?if there where i can find in admin panel?

**Comment by aimeos** [comment]
Not in the admin panel yet. You have to upload the CSV file to your server into the configured directory and run the job controller for importing the file: https://aimeos.org/docs/Developers/Controller/Import_products_from_CSV

**Comment by kras95** [comment]
@srigovind30 If you want to implement it I suggest looking at how they made the coupon code CSV import:
https://github.com/aimeos/ai-admin-jqadm/blob/master/src/Admin/JQAdm/Coupon/Code/Standard.php

Override the save() method to call a custom storeFile() method similar to coupon code import in this class:
https://github.com/aimeos/ai-admin-jqadm/blob/master/src/Admin/JQAdm/Product/Standard.php

Add a file upload option to the product listing template:
https://github.com/aimeos/ai-admin-jqadm/blob/master/templates/admin/jqadm/product/list.php

Just make sure the CSV is thrown in the correct directory, should be something like this:
```
/**
* Stores the uploaded CSV file containing the products
*
* @param array $files File upload array including the PSR-7 file upload objects
*/
protected function storeFile( array $files )
{
  $file = $this->val( $files, 'code/file' );
  
  if( $file == null || $file->getError() === UPLOAD_ERR_NO_FILE ) {
    return;
  }
  
  $this->checkFileUpload( $file );
  
  $context = $this->context();
  $fs = $context->fs( 'fs-import' );
  $location = 
  $dir = $context->get( 'controller/jobs/product/import/csv/location', 'product' ) . '/' . $context->locale()->getSiteItem()->getCode();
  
  if( $fs->isdir( $dir ) === false ) {
	  $fs->mkdir( $dir );
  }
  
  $fs->writes( $dir . '/' . $file->getClientFilename(), $file->getStream()->detach() );
}
	

````

**Comment by kras95** [comment]
I saw that this was an open issue, didn't realize it was implemented.
Also didn't notice how old this issue was.
