### ISSUE TITLE
Uncaught TypeError: e.cloneNode is not a function

### ISSUE THREAD

**Issue by Cyber-Devs** [aimeos/ai-admin-jqadm#203]
**Environment**
1. Version (e.g. aimeos-dev-master)
2. Integration (Larave)
3. System (Linux, Mac, Windows)
**Expected behavior**
jquery Uncaught TypeError: e.cloneNode is not a function
+
jQuery.Deferred exception: e.cloneNode is not a function Cn.prototype.$mount/r<@https://cdn.jsdelivr.net/combine/npm/bootstrap@5/dist/js/bootstrap.bundle.min.js,npm/vue@2/dist/vue.min.js,npm/vue-select@3/dist/vue-select.min.js,npm/flatpickr@4,npm/flatpickr@4/dist/l10n/index.min.js,npm

**Comment by aimeos** [comment]
When does that happen? Can you please provide a step by step guide?

**Comment by Cyber-Devs** [comment]
After the last update from yesterday this error arise and in jquery admin did not show any order as well nothing work which related to query, console error.
TypeError: e.cloneNode is not a function. (In 'e.cloneNode(!0)', 'e.cloneNode' is undefined)

its seen that jQuery have a bit complexion with new cue components on mount.
I regenerated all the possible way but did not found the clue.

**Comment by Cyber-Devs** [comment]
just with a fresh dev-master have the same issue, its have complection  with jsdelivr-separatorjs,  arise this issue from last update.

error->
Uncaught TypeError: e.cloneNode is not a function
    at jsdelivr-separator.js:1
    at Cn.$mount (jsdelivr-separator.js:1)
    at Cn.t._init (jsdelivr-separator.js:1)
    at new Cn (jsdelivr-separator.js:1)
    at Object.vue (js?locale=en:4787)
    at HTMLDivElement.<anonymous> (js?locale=en:5631)
    at Function.each (jquery.min.js:2)
    at S.fn.init.each (jquery.min.js:2)
    at HTMLDocument.<anonymous> (js?locale=en:5629)
    at e (jquery.min.js:2)

**Comment by aimeos** [comment]
Thanks, problem has been solved in dev-master
