### ISSUE TITLE
Product lists

### ISSUE THREAD

**Issue by exemplari** [aimeos/ai-admin-jqadm#204]
**Environment**
1. Version (e.g. 2017.10) - 2021.07.*-dev
2. Integration (Laravel, TYPO3, Symfony, SlimPHP or Flow) - laravel , aimeos-laravel
3. System (Linux, Mac, Windows) - linux (docker)

**Describe the bug**
Product grids are insane. 

**To Reproduce**
Example /admin/default/jqadm/search/product. 
Set status from 'all' to 'enabled', click search glass. 
Then click next to go to page 2, it resets to 'all' status. 

**Expected behavior**
Page 2 of Enabled products. Instead of Page 2 of All Products.

**Screenshots**

**Additional context**
Also go to the catalog page 
navigate to the products grid.  
/admin/default/jqadm/get/catalog/2?locale=en#product
It incorrectly says all are 'enabled'. 
Clicking downs shows some are disabled.
These search filters also do not work.

**Additional context**
Product grid enable a column, like 'created date'. 
Sort by created date. 
Go to page 2 and the created date sort is gone.

**Comment by aimeos** [comment]
Thanks for your report.

We can confirm that the filter, sorting and additional columns are gone when moving to the next page.

For the reported behavior in the catalog product subpart we were not able to reproduce that. Can you make a video showing the behavior?

**Comment by aimeos** [comment]
Filter, sortation and columns are fixed in dev-master and 2021.07.x-dev now

**Comment by exemplari** [comment]
Thanks, the main product grid is working great.

As to the catalog-products, here are a few screenshots. You'll see product id 190 shows 'enabled' when viewed through the catalog. Click through and it is disabled. 

![catalog-products](https://user-images.githubusercontent.com/541161/135441496-3c48848d-7440-492c-b501-e91a8c3b4021.PNG)

![product-190](https://user-images.githubusercontent.com/541161/135441503-3a65440a-c2ec-46ce-8539-1aaee83426dc.PNG)

**Comment by aimeos** [comment]
These are two different status values, the first one refers the mshop_catalog_list.status value while the second to the mshop_product.status value

**Comment by exemplari** [comment]
Understood. The fact that the mshop_catalog_list.status is there seems questionable. Wont it always be Enabled. There would be no point of having this information here.

**Comment by aimeos** [comment]
A disabled product state is shown by a strike-through product label
