### ISSUE TITLE
Error in the basket after user has been deleted

### ISSUE THREAD

**Issue by zherdev-artem** [aimeos/ai-admin-jqadm#207]
**Environment**
1. Version 2021.10
2. Integration Laravel

**Describe the bug**
The user basket is alive even after the user has been deleted.
Also, the basket keeps deleted customer.id which occurs an error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a user.
2. Add some products to the basket as this user.
3. Delete this user.
4. See errors

**Expected behaviour**
Clear basket session when the user has been deleted or delete customer.id from the basket.

**Comment by aimeos** [comment]
The basket is session based and it's not expected that the user is deleted during the session of that user is alive.

**Comment by aimeos** [comment]
Why do you delete the user at all?
If it's easy to fix then we are happy to merge a PR.

**Comment by zherdev-artem** [comment]
Hi, what about this?

app/vendor/aimeos/ai-controller-frontend/controller/frontend/src/Controller/Frontend/Customer/Standard.php:57

```
try {
    $this->item = $this->manager->get( $userid, [], true );
} catch(\Aimeos\MShop\Exception $e) {
    \Aimeos\Controller\Frontend::create( $context, 'basket' )->clear();
    throw $e;
}
```

**Comment by aimeos** [comment]
Guess, this is the wrong place for checking because if the user doesn't exist any more, bootstrapping in Aimeos Laravel package won't set the user ID in the context and this code will never be executed.

**Comment by zherdev-artem** [comment]
Ok, what about this?

app/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Base/Context.php
Move setUser only if user not null.
```
if( ( $user = Auth::guard( $guard )->user() ) !== null ) {
	$context->setEditor( $user->name );
        $context->setUserId( $user->id );
} elseif( $ip = \Request::ip() ) {
	$context->setEditor( $ip );
}
```

What is the purpose of the current condition, if the user may not exist?
```
if( ( $userid = Auth::guard( $guard )->id() ) !== null ) {
	$context->setUserId( $userid );
}
```

**Comment by aimeos** [comment]
Guards are explained here: https://laravel.com/docs/8.x/authentication

**Comment by zherdev-artem** [comment]
Hi, in the previous message I ask why you need especially get an id by Auth::guard( $guard )->id() which may get you the wrong result.

app/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php:204 (Laravel 6)
```
public function id()
{
    if ($this->loggedOut) {
        return;
    }

    return $this->user() // is null when user not exist
                ? $this->user()->getAuthIdentifier()
                // but session is alive and it return ID for deleted user
                : $this->session->get($this->getName());
}
```

instead Auth::guard( $guard )->user() return null when user deleted, even with alive session.

So, the user id will not go to context when the user is deleted.
```
protected function addUser( \Aimeos\MShop\Context\Item\Iface $context ) : \Aimeos\MShop\Context\Item\Iface
{
$key = collect( config( 'shop.routes' ) )->where( 'prefix', optional( Route::getCurrentRoute() )->getPrefix() )->keys()->first();
$guard = data_get( config( 'shop.guards' ), $key, Auth::getDefaultDriver() );

if( ( $user = Auth::guard( $guard )->user() ) !== null ) {
	$context->setEditor( $user->name );
          $context->setUserId( $user->id );
} elseif( $ip = \Request::ip() ) {
	$context->setEditor( $ip );
}

return $context;
}
```
Basket will without deleted user id and error not occur.

**Comment by aimeos** [comment]
The `Auth::guard( $guard )->id()` code was introduced by a 3rd party contribution.

If changing to `Auth::guard( $guard )->user()` fixes the problem and has no other negative consequences, we are fine and will merge a PR from you :-)
