### ISSUE TITLE
Product page: base data: description: help text

### ISSUE THREAD

**Issue by jsdmind** [aimeos/ai-admin-jqadm#21]
So far the [help text] (https://github.com/aimeos/ai-admin-jqadm/blob/b8af6c3a16ef58aec894c44705d5b556a6ec71c3/admin/i18n/en.po#L790)  is:

> Internal article name, will be used on the web site if no product name for the language is available

I suggest to note that it will not be searched. Thus it is IMHO imperative to add entries under "text" for each language.

**Comment by aimeos** [comment]
It's a bit more difficult: It won't be used for searching if product names in other languages are available. If not, it's used.

**Comment by aimeos** [comment]
Would that be more clear?

> Internal article name, will be used on the web site and for searching only if no other product names in any language exist

**Comment by aimeos** [comment]
Text has been changed in dev-master
