### ISSUE TITLE
__clone method called on non-object

### ISSUE THREAD

**Issue by Cyber-Devs** [aimeos/ai-admin-jqadm#210]
**Environment**
1. Version (dev-master, laravel8.*)
2. Operating system (Linux, Mac)

vendor/aimeos/ai-admin-jqadm/admin/jqadm/src/Admin/JQAdm/Product/Media/Standard.php:258

**$mediaItem->addListItem( 'attribute', ( clone $litem )->setId( null ) )**;

**Comment by aimeos** [comment]
Thank you for your issue report!
The problem has been fixed: https://github.com/aimeos/ai-admin-jqadm/commit/519ebce8d19e96a7c4cc860aee48b28dc1febdf3

**Comment by Cyber-Devs** [comment]
thanks  alot,
