### ISSUE TITLE
Product creation, put all needed data in one tab

### ISSUE THREAD

**Issue by tylik1** [aimeos/ai-admin-jqadm#213]
**Is your feature request related to a problem?**
Product creation is done on a constant basis, and it is crucial to make it fast for the user. Currently one has to switch between different tabs to populate media, description, product name, price etc.

**Describe the solution you'd like**
Is there a way to alter new product set up, so that all needed data is in one tab, without having to click through different tabs?

**Describe alternatives you've considered**
Worked in other CMS, where all product population is  structured in one page/tab

**Additional context**
Let's say I want to populate a product description. I have to click "Texts" and then additionally to click + button. Which are 2 additional steps. Also in the end I would like to validate all data for the product, and agian I have to go through different tabs which is not intuitive and takes more time.

Is it possible for me to alter the code, without much effort, so that I will have all needed data for product population in one tab and visible?

**Comment by aimeos** [comment]
You can use a custom template for the product detail view in the admin backend that contains only the fields you need.

Aimeos is very flexible in what you can do so it's not limited to a fixed set of data like one name and one description with one price. Instead, you can add as many texts, images, prices, etc. to product as you need.
