### ISSUE TITLE
An error occurs when placing a product in a category

### ISSUE THREAD

**Issue by Ameeko** [aimeos/ai-admin-jqadm#214]
**Environment**
Latest version
https://admin.demo.aimeos.org/admin/nope/jqadm/get/catalog/479?locale=en#product

**Describe the bug**
If I want to put a product into a category, the admin is not working properly.
If I press the + sign, a new line will appear where nothing can be done.
I have to press the save button so the product line is saved blank.
Then I can edit it with the pencil icon, so I can finally open the product selector, but here's some z-index problem because the drop-down doesn't show up properly.

**To Reproduce**
https://admin.demo.aimeos.org/admin/nope/jqadm/get/catalog/479?locale=en#product

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/61547701/149092797-5f1434b5-df2b-46ea-86b0-f528f871bf03.png)

**Comment by aimeos** [comment]
Thank you for your bug report and we can confirm the problem.

**Comment by Ameeko** [comment]
Hello Aimeos!
When will this bug be fixed?
Currently, unfortunately, there is no way to manually put a product into a category, so admin cannot be used.

**Comment by Ameeko** [comment]
Due to this error, the admin cannot save if I want to put a product in the category.

**Comment by aimeos** [comment]
We will have a solution soon.
In the meantime, you can add products to categories in the "Category" subpanel of the product detail view.

**Comment by aimeos** [comment]
A new version including the bugfix has been tagged (aimeos/ai-admin-jqadm:2021.10.11)

**Comment by Ameeko** [comment]
Hello!
I upgraded jqadm to version 2021.10.11 but it still doesn't work properly.

**Cuts the bottom of the dropdown while selecting:**
![image](https://user-images.githubusercontent.com/61547701/152055248-20af0afa-f3e2-412f-8300-d376ac3b369b.png)

**After selection, it does not show what I selected:**
![image](https://user-images.githubusercontent.com/61547701/152055287-6f9855ac-f8eb-4a71-b31e-73ad5a1eb9d9.png)

**After saving it does not show what I selected:**
![image](https://user-images.githubusercontent.com/61547701/152055501-e017374a-706c-4e57-995a-bc51653ff2db.png)

**Comment by aimeos** [comment]
The clipping is a long-known problem and caused by CSS behavior. There's no real solution but we added a minimum height of the table so the problem isn't that obvious any more.

The problem saving the product ID is solved now. Please execute this to get the fixed version:
```
composer req aimeos/ai-admin-jqadm:2021.10.x-dev
```
