### ISSUE TITLE
ugly article url

### ISSUE THREAD

**Issue by Michi1978** [aimeos/ai-admin-jqadm#215]

**Comment by Michi1978** [comment]
ugly article and categorie urls
the url of the web links are mostling anding with /3?site=default ~ or and other ugly characters. this does not look fine. if i want to forward a weblink to my client and copy it from the shop, he get's the link with that uly ending. not possible to create and show the link without the ending? does this also influence the SEO result?

**Comment by aimeos** [comment]
The site parameter is only added if you enable SHOP_MULTISHOP and in this case, you can adapt the routing to create nicer URLs: https://aimeos.org/docs/latest/laravel/customize/#adapt-the-routing

This doesn't influence SEO results.
