### ISSUE TITLE
order number

### ISSUE THREAD

**Issue by Michi1978** [aimeos/ai-admin-jqadm#216]
**Is your feature request related to a problem?**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**
Any alternative solutions or features you've considered?

**Additional context**

**Comment by Michi1978** [comment]
order numbers
i'm comming from woocommerce. i always used order numbers with prefix B following by the year e.g. 2022 and starting number e.g. 0001. so it's B20220001. it's not possible to use a charceter prefix for aimeos? and also not possible to use a year? and also not possible for the final client to change it? onyl possible by my web developer?

**Comment by aimeos** [comment]
Customizing invoice numbers is described here: https://aimeos.org/tips/aimeos-2021-10-lts-release/
