### ISSUE TITLE
shipment notification

### ISSUE THREAD

**Issue by Michi1978** [aimeos/ai-admin-jqadm#217]
shipment notification
i come from woocommerce. there i have a list with all orders. and on the right, there is a button, i can check and cause an email with shipping notification with onyl one click without opening the order. so i just open the order list and can sent to my client with only one click a shipment notification without opening the order. this is very comforable and saves a lot of time. also possible to offer this for aimeos?

**Comment by aimeos** [comment]
Currently, it's not available out of the box. Instead, you have to the "invoice" tab in the detail view and set the delivery status accordingly. Then, an e-mail is sent to the customer.

You can adapt the order list view and add a button for that which triggers setting the delivery status by using the JSON Admin API. This is rather easy to implement.

**Comment by aimeos** [comment]
Since 2023.x, the admin backend supports bulk edits and this includes the delivery status. After changing the status, e-mails will be sent if configured for that delivery status
