### ISSUE TITLE
serch filed instead of small magnifying glass

### ISSUE THREAD

**Issue by Michi1978** [aimeos/ai-admin-jqadm#218]
if a client wants so search something in the shop (e.g. an special product) and can't find it, he uses normally the search button. all famous and big online shops offer a big search field directly on the top of the page, everybody can find without delay and can directyl start with typing the search words. aimeos doesn't offer an serach field of the middle top of the page. there is only a magnifying glass. but this is small and i didn't notice it first. and also didn't realise, that this is the search function at aimeos. if i click onto the magnifying glass, if come to an completly white page. this white page looks very strange and client is not sure, if he is still on the correct safe shop page and this is still a trustable page. if a client visits this first time, probably he will cancel it, as it looks like another dangerous web site and not as the online shop site, he visited.

**Comment by aimeos** [comment]
If you move the cursor to the magnifying glass, a search field opens where you can enter the name of the product.
The included theme is only one example and you can add the search filter also at the left column by adapting the template.
