### ISSUE TITLE
separted field for house number

### ISSUE THREAD

**Issue by Michi1978** [aimeos/ai-admin-jqadm#219]
in the cheout page, client has to leave his address. e.g. his street and street number. often, google autofill helps to fill the fields. but often it happens, that client doesn't check the auto filled adress carefully and forgets the house number. if there would be a extra field for the house number as mandatory field, it would be sure, client can't forget to leave the house number. and there would be no problem with shipping delay and returning shipment because of missing house number. posible fo offer an extra field for the house number?

**Comment by aimeos** [comment]
You can configure the fields that are mandatory using:
https://aimeos.org/docs/latest/config/client-html/checkout-standard/#billingmandatory

`order.base.address.address2` is usually used for house numbers.
