### ISSUE TITLE
The category tree admin is not working properly

### ISSUE THREAD

**Issue by Ameeko** [aimeos/ai-admin-jqadm#221]
**Environment**
https://admin.demo.aimeos.org/admin/nope/jqadm/get/catalog/478?locale=en

**To Reproduce**

The demo admin has the following tree structure:
**Products
+--test
   +-- --- Bakery Items
+--123123**

1) I click on the "test" element.
2) I click on the "+" sign.
3) New element name: "test1"
4) Save

The new category tree:
**Products
+--test
   +-- --- Bakery Items
   +-- --- test1 <-- this is correct
+--123123**

5) I click on the "test" element again.
6) I click on the "+" sign.
7) New element name: "test2"
8) Save

The new category tree:
**Products
+--test
   +-- --- Bakery Items
   +----- test1
+--123123
+--test2  <---- this is NOT correct, because I clicked on the "test" item**

**_If I do it all again, but I click TWICE on "test" element at point 5, it works fine._**

**Comment by aimeos** [comment]
Tested that locally and in the demo setup but we couldn't reproduce the issue.
If the new category node isn't placed under the correct parent node, it's likely that the parent ID has not been updated for some reason:

![image](https://user-images.githubusercontent.com/8647429/149899268-e648eefd-d57c-4f93-8713-9b209105d572.png)

**Comment by Ameeko** [comment]
Thanks for the reply.
I can see in yout screenshot that you didn't do what I described.
After **test1** has been created, click back to **test** element again and create **test2**.

**Comment by aimeos** [comment]
OK, understand the problem. Because **test** is already selected, you de-select **test** if you click on the category again and the new node is created below the root node instead of **test**.

**Comment by Ameeko** [comment]
You're right!
Thank you
