### ISSUE TITLE
On Editing->save variant article arise Error of duplicating on demo data

### ISSUE THREAD

**Issue by Cyber-Devs** [aimeos/ai-admin-jqadm#223]
**Environment**
1. Version (e.g. dev-master)
2. Integration (Laravel)
3. System (Linux, Mac, Windows)

**Describe the bug**
On **Editing->save** variant article can#t save and arise Error of duplicating on demo data 

**To Reproduce**
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '48-attribute-1.-default-' for key 'mshop_media_list.unq_msmedli_pid_dm_sid_ty_rid':
INSERT INTO "mshop_media_list" (
"parentid", "key", "type", "domain", "refid", "start", "end",
"config", "pos", "status", "mtime", "editor", "siteid", "ctime"
) VALUES (
?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
**["48","attribute|default|","default","attribute","",null,null,"[]",0,1,"2022-02-01 20:18:53","admintest@admin.com","1.","2022-02-01 20:18:53"]
#0 /xxx/vendor/aimeos/aimeos-core/lib/mshoplib/src/MShop/Common/Manager/Lists/Base.php(240): Aimeos\MW\DB\Statement\DBAL\Prepared->execute()**

**Comment by aimeos** [comment]
This usually happens if you assign the same attribute twice to a variant article.
