### ISSUE TITLE
Can't switch to new theme

### ISSUE THREAD

**Issue by Ameeko** [aimeos/ai-admin-jqadm#224]
**Environment**
Latest version

**Describe the bug**
I created a new theme, but if I select the new theme in the admin backend, the frontend will still load the css files from the default theme folder.

**To Reproduce**

1) **I made an extension** with the aimeos extension builder (Laravel theme 2021.x extension)

2) **I copied the contents of the zip** here: d:\work\myproject\ext\myextension

3) I ran these commands:
**composer update** (This copied the files properly)
**php artisan view:clear**
**php artisan aimeos:clear**

4) I did not modify the client/html/common/template/baseurl setting. Nothing is set.

5) **After modifying the theme on the admin backend and pressing the save button**..
![theme1](https://user-images.githubusercontent.com/61547701/152407618-2760d774-efca-44cb-8a4a-0d95cc394182.png)
... **the HTML source will still retrieve the CSS file from the default folder.**
![theme2](https://user-images.githubusercontent.com/61547701/152407632-df5176eb-8775-4eef-9fdb-85b1ccd3dc0a.png)

I would expect this path:
http://myproject.local/vendor/shop/themes/mytheme/aimeos.css

This is the **mshop_locale_site** table
![image](https://user-images.githubusercontent.com/61547701/152412992-709cac26-82c8-4a90-96c7-8a454d059722.png)

**Comment by aimeos** [comment]
You can't put the Laravel theme extensions into the ./ext/ folder because Laravel won't recognize the extension service provider in that case. Instead, you have to install the extension like any other Laravel package via composer. This is also described in the docs: https://aimeos.org/docs/latest/laravel/themes/#installation
