### ISSUE TITLE
Copied product ctime sort

### ISSUE THREAD

**Issue by exemplari** [aimeos/ai-admin-jqadm#225]
**Environment**
1. Version (e.g. 2017.10)
"aimeos/aimeos-laravel": "2021.10.*",
2. Integration (Laravel, TYPO3, Symfony, SlimPHP or Flow)
3. System (Linux, Mac, Windows)

**Describe the bug**
Products do not sort by created time when created via the copy product button.

**To Reproduce**
Click the copy button and save a new product.
![image](https://user-images.githubusercontent.com/541161/153197567-6dfa0647-dca2-4336-be63-53f473260f5a.png)

**Expected behavior**
I expect the copied new product to have a created time of Now.

**Screenshots**
The newly copied product has the same created time as the old product.

![image](https://user-images.githubusercontent.com/541161/153197743-6b1d25ac-a5ee-4f14-936d-7c1f63c63585.png)

In my particular case this becomes noticeable when trying to sort products by created time via the json frontend.

**Comment by aimeos** [comment]
Thanks for the hint!
The ctime field is not copied any more after this commit: https://github.com/aimeos/ai-admin-jqadm/commit/34f3318ed210352d88e20c0591e816d5201bab49

You can test the new version executing:
```
composer req aimeos/ai-admin-jqadm:2021.10.x-dev
```

**Comment by exemplari** [comment]
Thank!
