### ISSUE TITLE
CMS undo bug

### ISSUE THREAD

**Issue by Ameeko** [aimeos/ai-admin-jqadm#227]
Admin backend (CMS menu)

- I created a new page
- I wrote text
- I saved the changes
- I opened it again
- I pressed the "undo" button above the editing area

The editor is loading an incorrect state.
You can see that the subpage header appears in the editor.
This state is not working properly for example a "Container" element cannot be dropped into this state.

![cms-02](https://user-images.githubusercontent.com/61547701/153768924-3b752ec5-8edc-430e-8b82-4a651c577d3a.png)

**Comment by aimeos** [comment]
Updated to GrapesJS 0.17.29 which fixes the problem.
You can test by executing: `composer req aimeos/ai-cms-grapesjs:2021.10.x-dev`
