### ISSUE TITLE
Slow JS respond

### ISSUE THREAD

**Issue by Ameeko** [aimeos/ai-admin-jqadm#228]
Hello!
It happens very often that when I enter the admin interface, the "**/admin/default/jqadm/file/js?locale=en**" responds very slowly.
After 10-12 seconds, the response arrives and the page starts working.
There is no problem with internet speed and other websites.
Only this request is slow.
What is the problem?

![image](https://user-images.githubusercontent.com/61547701/154156331-f3954854-ccf2-4ac2-b65f-694a86d8451b.png)

![image](https://user-images.githubusercontent.com/61547701/154157156-69f9fb7c-e9eb-43c3-9c2a-87de4ffdf1b2.png)

**Comment by aimeos** [comment]
Do you use AWS or another cloud service?
The "file" action collects all CSS or JS files from the file system and sends them concatenated to the browser

**Comment by Ameeko** [comment]
I don't use AWS.
This is a standard web hosting service, the largest hosting company in my country. :(
Could it be a server setup problem?
The weird thing is that only this request is slow.

**Comment by aimeos** [comment]
All other requests only execute PHP files from the OPCache but this request actually reads several file from the disk.
It's likely that there's a problem with the read performance of small files.

**Comment by Ameeko** [comment]
Sorry to write about this again, but I'm already moving to the third hosting and it works poorly everywhere.
I really don't know how to solve this.

![image](https://user-images.githubusercontent.com/61547701/161384292-6bd4016f-2aac-4e12-81ef-db678da86087.png)

![image](https://user-images.githubusercontent.com/61547701/161384328-55938227-2144-4811-926f-06b28d7466f7.png)

**Comment by aimeos** [comment]
Do these providers all use the same infrastructure?

You can add some debug statements here to see where the time is wasted:
- https://github.com/aimeos/aimeos-laravel/blob/master/src/Aimeos/Shop/Controller/JqadmController.php#L35-L72
- https://github.com/aimeos/aimeos-core/blob/2021.10/lib/mwlib/src/MW/Jsb2/Standard.php
