### ISSUE TITLE
bulk delete option

### ISSUE THREAD

**Issue by rowild** [aimeos/ai-admin-jqadm#23]
I "play around" with 17.10 distibution, so I have no idea, if this is maybe already integrated in version 18.*. If so, please ignore!

It would be great to have the possibility to delete many entries at once. Currently, removing "attributes"(e.g.) is a nasty very click-rich endeavour...

Thanks!

**Comment by aimeos** [comment]
Do you mean in the list views?

**Comment by rowild** [comment]
Yes, I do. Sorry for being unclear, I should have mentioned that...

**Comment by aimeos** [comment]
It's not yet implemented but we will keep this issue open as a reminder
Thanks for your suggestion

**Comment by rowild** [comment]
Excellent, thank you! On that account, I would like to add that the toggling of items (en-, disabled) would also be great a feature that would fit well into the list view.

**Comment by aimeos** [comment]
Finally implemented and will be part of the next release
