### ISSUE TITLE
Can't add media for new product

### ISSUE THREAD

**Issue by ARA1985** [aimeos/ai-admin-jqadm#233]
**Environment**
1. Version (e.g. 2021.10)
2. Integration (Laravel)
3. System (Linux, Mac)

**Describe the bug**
"Add New Image" button not working.

**Screenshots**
https://monosnap.com/file/TrjegxLDdwnTXabXujoL0RBN02NjuV

**Comment by aimeos** [comment]
We can't reproduce any issue neither in 2021.10 nor in 2022.04. Do you have any errors in your browser console?
A known issue is that browsers sometimes need a long time until they display the file selection dialog.

**Comment by ARA1985** [comment]
Sorry. The problem was in the browser. I checked other sites, the form element for uploading files does not work.
