### ISSUE TITLE
Missing parameter: resource

### ISSUE THREAD

**Issue by Cyber-Devs** [aimeos/ai-admin-jqadm#235]
**Environment**
1. Version (dev-master)
2. Integration (Laravel9+)
3. System (Linux, Mac, Windows)

Missing required parameter for [Route: aimeos_shop_jsonadm_get] [URI: admin/{site}/jsonadm/{resource}/{id?}] [Missing parameter: resource].

**Comment by aimeos** [comment]
Please run `composer up` again as we've pushed a commit with fixes a few minutes ago.

**Comment by Cyber-Devs** [comment]
resolved 👍
