### ISSUE TITLE
Error while uploading the image

### ISSUE THREAD

**Issue by pamirsawar** [aimeos/ai-admin-jqadm#238]
**Environment**
1. Version (2022.07.2)
2. Integration (Laravel)
3. System (Windows)

**Describe the bug**
While trying to upload image in the media tab it shows and error for some images.

**To Reproduce**
1. Go to 'catalog>products>'
2. Click on 'product'
3. Scroll down to 'media tab' and upload an picture (it happens for mostly for .png files)

![Screenshot_16](https://user-images.githubusercontent.com/53907015/185109532-cf4ef0f7-13b7-46ef-85ba-385d9d49683a.png)

**Comment by aimeos** [comment]
You can try `aimeos/aimeos-core:2022.07.x-dev` which contains now the `imagepalettetotruecolor()` call.
