### ISSUE TITLE
How to add option from admin for choose file that will be reflected in frontend of product page

### ISSUE THREAD

**Issue by HashSourabh** [aimeos/ai-admin-jqadm#239]
**Is your feature request related to a problem?**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**
Any alternative solutions or features you've considered?

**Additional context**

**Comment by HashSourabh** [comment]
I want clarification regarding the choose file feature from frontend.

**Comment by aimeos** [comment]
There are PR for implementing that feature but they are of low quality so we didn't merge them yet:
- https://github.com/aimeos/ai-admin-jqadm/pull/202
- https://github.com/aimeos/ai-client-html/pull/153
