### ISSUE TITLE
Wrong help text for the language selector in the text sub-panels

### ISSUE THREAD

**Issue by rowild** [aimeos/ai-admin-jqadm#24]
This issue was opened here: https://github.com/aimeos/aimeos-typo3/issues/64
but actually belongs to this repository.

Will provide a PR for these files:
admin/jqadm/templates/attribute/item-text-standard.php
admin/jqadm/templates/catalog/item-text-standard.php
admin/jqadm/templates/product/item-text-standard.php
admin/jqadm/templates/service/item-text-standard.php

**Comment by rowild** [comment]
I don't know how to handle po-files. Followed the guide here:
https://aimeos.org/docs/Developers/Add_translations
but that does not cover how to implement new strings in all languages automatically, even if their translation remains empty at the moment.
Would like to know more about that process...

**Comment by aimeos** [comment]
That's something we have to do:
```
phing i18n
tx push -s
```
The later command transfers the new translations to Transifex where you can translate them into all available languages (https://www.transifex.com/aimeos/public/)

**Comment by aimeos** [comment]
Your PR has been merged. Thanks again!

**Comment by rowild** [comment]
Thank you!! - So, just to make sure: does it then still make sense to include the manually changed .po-files or not?

**Comment by aimeos** [comment]
It's not the preferred way. We will try to push those translations into Transifex as well

**Comment by rowild** [comment]
Ok, so in future I better stay away from commiting .po-files in a PR, right?

**Comment by aimeos** [comment]
Yes, you shouldn't change the .po files. As soon as we updated Transifex sources via `tx push`, you will be able to add translations for the new string, e.g. for your example: https://www.transifex.com/aimeos/aimeos-core/translate/#de/admin/133136845?translated=no

**Comment by rowild** [comment]
Understood. In this case you provided the string. 

But my question is: if **I** add a new help text (e.g.) with a yet not existing string, how do I tell you, that the .po-files need updated? Is there a special workflow that should be followed to inform the core developers know or should it just be a "NOTE: new .po string necessary" in the PR? (It seems a PR that requires a new string, but does not provide everything that in necessary to also update the po-files, seems... incomplete...). Or am I just not allowed to add a new string, unless not before discussion it with you? (which would seem logical...)

Sorry, as you can tell, I lack a lot of experience...

**Comment by aimeos** [comment]
Usually, we have a look at every PR we are merging. When we see new texts, we will push them to Transifex. But you can always add a note that a new text needs to be translated
