### ISSUE TITLE
homepage isn't responding properly

### ISSUE THREAD

**Issue by aroy1245** [aimeos/ai-admin-jqadm#240]
after filling up the registered detail, verify email function sends an email verification link to the user's mail after verifying the new account, and it redirects to the admin page and then if the user goes to the home page it shows some error. Really sorry for my English. And please fix this issue as fast as you can, thanks you.

**Comment by aimeos** [comment]
Can you show a screenshot of that error or do  you have a stack trace?

**Comment by aimeos** [comment]
Can you please install the latest version from the 2022.07 branch:
```
composer req aimeos/aimeos-laravel:2022.07.x-dev
```
