### ISSUE TITLE
error to add new currency

### ISSUE THREAD

**Issue by pritom24** [aimeos/ai-admin-jqadm#243]
**Environment**
1. Version (e.g. 2017.10)
2. Integration (Laravel, TYPO3, Symfony, SlimPHP or Flow)
3. System (Linux, Mac, Windows)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by pritom24** [comment]
![Screenshot (31)](https://user-images.githubusercontent.com/57866064/201894905-222160e2-3b89-4fdb-8343-9609240df61b.png)

**Comment by pritom24** [comment]
![Screenshot (32)](https://user-images.githubusercontent.com/57866064/201895521-18e3d1c3-ef54-4c67-b50b-6337683f2522.png)

**Comment by aimeos** [comment]
Please have a look into the Log panel for the error details.
