### ISSUE TITLE
"Delete this entry" button not working

### ISSUE THREAD

**Issue by Tantacula** [aimeos/ai-admin-jqadm#245]
**Environment**
1. Version (e.g. dev-main)
2. Integration (Laravel)
3. System (Linux)

"Delete this entry" button in "Types -> CMS List" not working.

![image](https://user-images.githubusercontent.com/1346989/204531731-bf3bb40b-fe9c-4bc6-8309-2e26ee501ffd.png)

**Comment by aimeos** [comment]
Thanks, it's fixed now in `aimeos/ai-cms-grapesjs:2022.10.x-dev`. Can you please install and test?
```
composer req aimeos/ai-cms-grapesjs:2022.10.x-dev
```

**Comment by Tantacula** [comment]
It works now, thank you
