### ISSUE TITLE
Invalid "Price properties" name

### ISSUE THREAD

**Issue by Tantacula** [aimeos/ai-admin-jqadm#248]
**Environment**
1. Version: 2022.10
2. Integration: Laravel

**Describe the bug**
Menu section "type" has two "Product properties" items, one of them opens price property types.
![image](https://user-images.githubusercontent.com/1346989/206134291-f1875aee-108a-4c1f-afb1-c5562cb9df81.png)

**Comment by aimeos** [comment]
Thanks for the hint! The translation has been fixed and it's available in `aimeos/ai-admin-jqadm:dev-master` and `aimeos/ai-admin-jqadm:2022.10.x-dev` and will be part of the next minor release.
