### ISSUE TITLE
Tags issues

### ISSUE THREAD

**Issue by Tantacula** [aimeos/ai-admin-jqadm#249]
**Environment**
1. Version 2021.10
2. Integration Laravel

**Describe the bug**
How can I use "tags" feature? Currently tags are not available in products and categories. Also I see item with status "tag" in menu "Tags -> product lists", but when I open it there is no domain "Tag" available in select input.

**Comment by aimeos** [comment]
In principle, tags are implemented and available but not used up to now. There's no way to assign them in the backend yet and the frontends doesn't use them anywhere.
If you have a good use case for the frontend and are willing to contribute code, we will make them available in the backend too :-)
