### ISSUE TITLE
Duplicated Payment Status: deleted

### ISSUE THREAD

**Issue by maynor96** [aimeos/ai-admin-jqadm#250]
Hello!

Payments have the status "**deleted**" twice: the codes of these statuses are: **pay:0** and **pay:7**

https://github.com/aimeos/ai-admin-jqadm/blob/31ed13aa35440cfd9c6e1c984e23ac4aec4d3be3/i18n/en.po#L2138

https://github.com/aimeos/ai-admin-jqadm/blob/31ed13aa35440cfd9c6e1c984e23ac4aec4d3be3/i18n/en.po#L2160

Best regards!

**Comment by aimeos** [comment]
Thanks for the hint, it's fixed now in dev-master and 2022.10.x-dev
