### ISSUE TITLE
Error Target class [aimeos.context] does not exist.

### ISSUE THREAD

**Issue by DevoidBark2** [aimeos/ai-admin-jqadm#261]
$context = app( 'aimeos.context' )->get();
$cls = new \Aimeos\MShop\Catalog\Manager\Standard($context);

What does he want me to connect, I don’t understand, help, please?

**Comment by aimeos** [comment]
Don't use Laravel code in the Aimeos admin backend. Instead use:
```php
$manager = \Aimeos\MShop::create( $this->context(), 'catalog' );
```

**Comment by DevoidBark2** [comment]
$this is not available to me since it is a regular php file, in which I receive data (namely a feed) through redis, which scab in this file and add new products, characteristics to the database

Отправлено из мобильной Почты Mail.ru


среда, 23 августа 2023 г. в 17:34 +03:00 от ***@***.***  ***@***.***>:

**Comment by aimeos** [comment]
You should open a thread in the Aimeos forum if you want to know how you can achieve something as the Github issues are only for potential bug reports or feature requests
