### ISSUE TITLE
Update additional field for users

### ISSUE THREAD

**Issue by unnimaya-seeroo** [aimeos/ai-admin-jqadm#263]
Added some extra fields for users in database, we could able to show the values in Admin->users->customer->detail page.
But when we edit the details the newly added fields  not get updated. We are working on the file  Admin/jqadm/customer/standard.php
Please explain the steps to update newly created fields from Admin ->user->customer module

We have change the sql query in Mshop/customer.php file but getting "Invalid parameter number: number of bound variables does not match number of tokens"
Please explain
@aimeos

**Comment by aimeos** [comment]
If you want to extend the customer manager to store additional data, create a decorator like described here:
https://aimeos.org/docs/latest/models/extend-managers/

**Comment by unnimaya-seeroo** [comment]
I created a decorator as per the document , and included in mshop.php file but it seems like it checking on mshop_customer  table, and when i add additional fields in mshop_customer table it retruns the error Item with ID "2" in "customer.id" not found.
please advice !!
