### ISSUE TITLE
Admin Order details: product delivery/payment statuses are not saved 

### ISSUE THREAD

**Issue by akropivko** [aimeos/ai-admin-jqadm#264]
**Environment**
1. Version - 2023.07
2. Integration - Laravel
3. System - Windows10

**Describe the bug**
Admin Order details: product delivery/payment statuses are not saved on Save btn, see attached snapshot
File -  templates/admin/jqadm/order/item.php

**To Reproduce**
1. Go to Admin/Sales/Order details
2. Change Payment/Delivery status in Products block
3. Click the Save btn
4. The status fields are emty again

**Expected behavior**
The status fields should have the selected status

**Screenshots**
![Screenshot_4](https://github.com/aimeos/ai-admin-jqadm/assets/66216139/f189a35a-9fcf-4ab6-bfa6-65fcf5d4ed9e)

**Comment by aimeos** [comment]
Thanks for your hint! The problem was not saving the data but it wasn't shown afterwards.
This is fixed now and a new version of the aimeos/ai-admin-jqadm package has been tagged.

**Comment by akropivko** [comment]
Could you please advice me how can I apply this tag into my current Aimeos project? Composer?..

**Comment by aimeos** [comment]
Just run `composer up` :-)
