### ISSUE TITLE
Invalid name "customer.id" Error

### ISSUE THREAD

**Issue by unnimaya-seeroo** [aimeos/ai-admin-jqadm#265]
1.   "aimeos/aimeos-laravel": "2023.04.*",
2. Laravel
3.Windows

Trying to extend the Customer manager.
Created corresponding decorator file .
Getting the below error
  "aimeos/aimeos-laravel": "2023.04.*",
Please explain @aimeos 
![Invalid-name-customer-id-](https://github.com/aimeos/ai-admin-jqadm/assets/83745002/d87a8f09-b5ab-414c-ab19-0d4b51bf4363)

**Comment by aimeos** [comment]
Please post your code in the Aimeos forum and share the stack trace via Flare ("Share" link at the top).
Github issues are only for bug reports and feature requests.
