### ISSUE TITLE
Visited categories remain highlighted

### ISSUE THREAD

**Issue by akropivko** [aimeos/ai-admin-jqadm#266]
**Environment**
Version - 2023.07
Integration - Laravel
System - Windows10

**Describe the bug**
Visited categories remain highlighted - see screenshort

**To Reproduce**
1. Go to Admin / Catalog / Categories
2. Click several new created categories,

**Expected behavior**
Inactive category should not be highlighted.

**Screenshots**
![Screenshot_6](https://github.com/aimeos/ai-admin-jqadm/assets/66216139/44f8e0ac-98f5-40a5-9aec-41a838314d39)

**Comment by aimeos** [comment]
We can't reproduce the problem but are pretty sure that it's possible.
Our plan is to replace this jQuery based component in the next version with a VueJS tree component which works much better.
