### ISSUE TITLE
How can I store files in public/uploads folder

### ISSUE THREAD

**Issue by unnimaya-seeroo** [aimeos/ai-admin-jqadm#267]
**Environment**
1. Version : 2023.04
2. Integration Laravel
3. System Windows
**Describe the bug**
Iam generating a pdf file while editing the user detail from admin.
Using DOM pdf to generate.
How can i stored the  generated pdf in a folder (public/uploads)
and also i need to add a provision to view the pdf generated, so how can i get the url to access the pdf

"$pdf = Pdf::loadView('seller.agreement')->save('public/uploads/');"
@aimeos

**Comment by aimeos** [comment]
For questions how to implement something, please open a topic in the Aimeos forum: https://aimeos.org/help
The Github issues are only for bug reports and feature requests
