### ISSUE TITLE
"Allow custom price" do nothing

### ISSUE THREAD

**Issue by akropivko** [aimeos/ai-admin-jqadm#269]
**Environment**
aimeos/ai-admin-jqadm  2023.07.8 
Laravel
Windows

**Describe the bug**
"Allow custom price" do nothing

**To Reproduce**
1. Product details 
2. Check "Allow custom price" and click Save btn
3. No result: the checbox remains unchecked, frontend without any changes

**Expected behavior**
Checkbox should be checked, some new field for custom price on the frontend/

**Screenshots**
![Screenshot_16](https://github.com/aimeos/ai-admin-jqadm/assets/66216139/35185ec9-68f9-4025-b333-9d928e27dca7)

**Comment by aimeos** [comment]
Thanks for the hint! The problem has been fixed in dev-master and 2023.07.x-dev
