### ISSUE TITLE
Product Property Types "Position" option do nothing

### ISSUE THREAD

**Issue by akropivko** [aimeos/ai-admin-jqadm#270]
**Environment**
aimeos/ai-admin-jqadm 2023.07.8
Laravel
Windows

**Describe the bug**
Changing positions of Product Property Types items does not affect neither admin no fronend - see screenshots

**To Reproduce**
See screenshots

**Screenshots**
![Screenshot_18](https://github.com/aimeos/ai-admin-jqadm/assets/66216139/24e3d6ea-1155-492e-832b-217da62e2db6)
![Screenshot_19](https://github.com/aimeos/ai-admin-jqadm/assets/66216139/d139456a-cffd-45d7-9ebf-c5927f32b047)
![Screenshot_20](https://github.com/aimeos/ai-admin-jqadm/assets/66216139/aca6dbfe-cc65-4f7a-84b1-8389156c206e)

**Comment by aimeos** [comment]
This is already fixed in dev-master and 2023.07.x-dev and will be part of the next release. You can test it yourself if you execute to:
```
composer req aimeos/ai-client-html:2023.07.x-dev
```
