### ISSUE TITLE
The entire attribute values not showing in product detail page

### ISSUE THREAD

**Issue by unnimaya-seeroo** [aimeos/ai-admin-jqadm#272]
**Environment**
1. Version (2023)
2. Integration (Laravel)
3. System (Linux)

**Describe the bug**
On the global admin dashboard, I set up a
Type > Attribute called "State-Certification". Then, I went to Catalog > Attributes and
created an Attribute for each State in the nited States. There are 50 states in the
United States, so I created 50 attributes,ne for each state.In the Product Detail page for Product I went to the Characteristics panel. I added three Sates as Attributes.
Problem: In the drop down list of “State-Certification” attributes, the list
does not show all the States... It only hows about half of the States for selection, and not the entire list.
![image](https://github.com/aimeos/ai-admin-jqadm/assets/83745002/2a838aef-78d6-45cb-b51c-bd01d50f93af)
@aimeos

**Comment by aimeos** [comment]
It's a combo-box with search as you type capabilities because there can be thousands of values
