### ISSUE TITLE
Wrong label on the catalog detail page

### ISSUE THREAD

**Issue by akropivko** [aimeos/ai-admin-jqadm#273]
**Environment**
Version - 2023.07
Integration - Laravel
System - Windows10

**Describe the bug**
Wrong label or help note on the catalog detail page
"Stock level"/"Internal article name"??
![Screenshot_24](https://github.com/aimeos/ai-admin-jqadm/assets/66216139/369bb6f0-c9a8-4480-af6f-b30e86de33be)

**Comment by aimeos** [comment]
Thanks for spotting, help text has been changed now (available in dev-master and 2023.07.x-dev)
