### ISSUE TITLE
Missing media for variants when "select" type was duplicated

### ISSUE THREAD

**Issue by akropivko** [aimeos/ai-admin-jqadm#274]
**Environment**
Version - 2023.07
Integration - Laravel
System - Windows10

**Describe the bug**
Missing media for variants when "select" type was duplicated

**To Reproduce**
1. Create "select" type product item and a couple of var. for it.
2. Duplicate it. See the screenshot
![Screenshot_25](https://github.com/aimeos/ai-admin-jqadm/assets/66216139/5b5274fe-67ae-4444-9bea-13be6c2e9ca3)

**Comment by aimeos** [comment]
Copying selection products will create only variants with the same data as listed in the "Variant" tab and that means, no images, attributes, prices, etc. from the original variant articles are included.

**Comment by akropivko** [comment]
I see... Thanks.
