### ISSUE TITLE
Can not able to add more number of attributes in product detail section

### ISSUE THREAD

**Issue by unnimaya-seeroo** [aimeos/ai-admin-jqadm#276]
**Environment**
1. Version (2023)
2. Integration (Laravel)
3. System (Linux)

When we try to add more attributes in product detail page , the system allows only 11 attributes. thier is no + icon after this. do it has any limitation in attribute?
We need to add 50 attributes there.
![image](https://github.com/aimeos/ai-admin-jqadm/assets/83745002/6b059bb7-6ada-44a0-bc40-ff16e9c88f8d)
@aimeos

**Comment by aimeos** [comment]
You can add as many attributes as you want, there's no limitation. The "+" button is always at the top right of the table.
