### ISSUE TITLE
Rename the sidemenu

### ISSUE THREAD

**Issue by unnimaya-seeroo** [aimeos/ai-admin-jqadm#277]
Environment
Version - 2023.07
Integration - Laravel
System - Windows11

We couldn't able to rename the left side menu label by navbar file.
@aimeos

**Comment by aimeos** [comment]
Navbar items can be translated by using "admin" as translation domain:
https://github.com/aimeos/ai-admin-jqadm/blob/master/templates/admin/jqadm/page.php#L195

The translation keys are listed in this config file:
https://github.com/aimeos/ai-admin-jqadm/blob/master/config/admin/jqadm/navbar.php
