### ISSUE TITLE
No item found for conditions: Array ( [locale.site.code] => default )

### ISSUE THREAD

**Issue by HadiHilal** [aimeos/ai-admin-jqadm#279]
**Environment**
1. Version (e.g. 2023.10)
2. Integration (Laravel)
3. System (Linux)

**Comment by aimeos** [comment]
You've probably renamed the site with code "default" but didn't set the this configuration accordingly:
https://github.com/aimeos/aimeos-laravel/blob/master/config/shop.php#L176
