### ISSUE TITLE
Impossible to change basket plugin status

### ISSUE THREAD

**Issue by akropivko** [aimeos/ai-admin-jqadm#280]
**Environment**
Version - 2023.07
Integration - Laravel
System - Windows10

**Describe the bug**
Impossible to change basket plugin status, see the screenshot below
![basket_plugin](https://github.com/aimeos/ai-admin-jqadm/assets/66216139/27e7dab8-dd6b-4563-95d0-d6bafa9d746c)

**Comment by aimeos** [comment]
Thanks for noticing! The bug is now fixed in aimeos/aimeos-core:2023.07.x-dev resp. dev-master and will be part of the next release.
