### ISSUE TITLE
Order payment/delivered dates are not saved, as well as billing info

### ISSUE THREAD

**Issue by akropivko** [aimeos/ai-admin-jqadm#281]
**Environment**
Version - 2023.07
Integration - Laravel
System - Windows10

**Describe the bug**
Order payment/delivered dates are not saved, as well as billing info, see the screenshot
![oders](https://github.com/aimeos/ai-admin-jqadm/assets/66216139/e017a68f-4fc0-4737-b3a7-bfb593108aa8)

**Comment by aimeos** [comment]
You have a JS error somewhere, please have a look into the browser console.

**Comment by akropivko** [comment]
sorry. thanks.
