### ISSUE TITLE
An empty list of service providers is encountered when attempting to create a new service

### ISSUE THREAD

**Issue by akropivko** [aimeos/ai-admin-jqadm#283]
**Environment**
Version - 2023.07
Integration - Laravel
System - Windows10

**Describe the bug**
An empty list of service providers is encountered when attempting to create a new service. Finally I've got the list, but the way to do this is a little bit strange, see the screenshot
![delivery](https://github.com/aimeos/ai-admin-jqadm/assets/66216139/438d7f9e-c530-44d9-8176-ef5a00e7875e)

**Comment by aimeos** [comment]
Thanks for the bug report!
We've fixed the problem in dev-master and 2023.10.x-dev and it will be part of the next release.
