### ISSUE TITLE
Attributes with status "disabled" are still available on the product details backend

### ISSUE THREAD

**Issue by akropivko** [aimeos/ai-admin-jqadm#284]
**Environment**
Version - 2023.07
Integration - Laravel
System - Windows10

**Describe the bug**
Attributes with status "disabled" are still available on the product details backend. You need to delete it to exclude from select box, see the attachment 
![attr](https://github.com/aimeos/ai-admin-jqadm/assets/66216139/9bc49065-227d-498f-8a2d-f35f5e5c2277)

**Comment by aimeos** [comment]
Makes sense: https://github.com/aimeos/ai-admin-jqadm/commit/aa4acb17a12e7a299365bed5ba7f5049ae47051b
