### ISSUE TITLE
New delivery service contains readonly fields

### ISSUE THREAD

**Issue by akropivko** [aimeos/ai-admin-jqadm#286]
**Environment**
Version - 2023.10.x-dev
Integration - Laravel
System - Windows10

**Describe the bug**
New delivery service contains readonly fields - see the screenshot
![Screenshot_58](https://github.com/aimeos/ai-admin-jqadm/assets/66216139/e85679dc-2209-4303-aec5-8591f5d4c8f5)

**To Reproduce**
1. Go to the backend and create a new delivery service

**Expected behavior**
All fields must be writeable

**Comment by aimeos** [comment]
Please update to the latest version as this is already fixed.
