### ISSUE TITLE
Purpose of Route Target Optin in product detail

### ISSUE THREAD

**Issue by unnimaya-seeroo** [aimeos/ai-admin-jqadm#288]
**Environment**
1. 2023.4
2. Laravel
3. Windows
Do we need to set up the route, controller, and view pages when adding url in the URL target option in catalog ->product detail
We have given a custom URL there given Route is not defined error in the website while loading.
Please explain.
@aimeos

**Comment by aimeos** [comment]
You can only add a route name you've defined in your `./routes/web.php` file in the `URL target` field and it will be used to generate URLs for that product instead of the `aimeos_shop_detail` route. Thus, you can implement custom pages for special products
