### ISSUE TITLE
Cms -> Select image: empty view

### ISSUE THREAD

**Issue by nvdid** [aimeos/ai-admin-jqadm#289]
**Environment**
1. Version 2023.10.8
2. Integration Laravel
3. System Linux

**Describe the bug**
When I try to upload image to CMS, I don't see the upload area. Apparently it's hidden (display: none).

**To Reproduce**
1. Go to 'http://localhost/admin/default/jqadm/create/cms?locale=en#content'
2. Click on 'content tab'
3. Click on 'add image icon'
4. Select image modal opens which is empty

**Expected behavior**
Upload area or select image

**Screenshots**

![image](https://github.com/aimeos/ai-admin-jqadm/assets/158066376/89c5bc6b-376c-4e5e-aadc-64ca1ef25f12)

![image](https://github.com/aimeos/ai-admin-jqadm/assets/158066376/5722930b-c433-4cbd-9dd2-013e3302cffa)

**Comment by aimeos** [comment]
You have to upload your images in the Media tab first and save once before the images are available in the content tab.

**Comment by nvdid** [comment]
Right. Didn't know that.
But I wonder why the upload area exists in DOM. Maybe left there from the past. Just want to point out if code refactor necessary. Otherwise we can close this issue.
Thanks

**Comment by aimeos** [comment]
GrapesJS has it's own file upload dialog but it's unsuitable because the uploaded file shouldn't be added directly to the page. Instead, responsive images have to be generated by the server and these images need to be added in an image srcset.
