### ISSUE TITLE
In aimeos TYPO3 extension's backend module: scrolling down not possible

### ISSUE THREAD

**Issue by merzilla** [aimeos/ai-admin-jqadm#29]
Hi,
in `"aimeos/aimeos-typo3": "^18.1",` it is not possible to scroll down in the jqadm module.
I use the latest TYPO3 LTS version 8.7.12. But scrolling was already broken before that, meaning at least 8.7.10, too.
I do not see any errors in browsers console.

Could you have a look at that, please?

Btw. would you recommend to use the GitHub repo as `dev-master` in composer?

Thx
merzilla

**Comment by aimeos** [comment]
Seems to be a problem only in the TYPO3 environment. Laravel works fine for example. We will have a look at that.

We wouldn't recommend using `dev-master` in general (especially not between October and January when we are doing all the breaking changes). But it's OK to use it in between stable release until the next stable version is available like the next one will be out in 2 weeks.

**Comment by merzilla** [comment]
Hi,
I can confirm it has to do with https://forge.typo3.org/issues/84522
In v8.7.10 scrolling still works.

Regards
merzilla

**Comment by merzilla** [comment]
With TYPO3 8.7.13 scrolling is still broken. But it seems not to be TYPO3 related. Could you check already if the aimeos CSS is responsible for that scrolling issue?

**Comment by aimeos** [comment]
None of the possible problematic CSS styles listed are used in Aimeos and we've found no CSS in the admin interface that causes the issue. Maybe you have more luck if you want to have a look yourself.

**Comment by aimeos** [comment]
We've finally found a workaround for the problem by setting
```
html, body {
    height: 100%;
    overflow: auto;
}
```
There's already a new version for 2018.04 available
