### ISSUE TITLE
Not a bug but - i think its not picking css or soemthing like that 

### ISSUE THREAD

**Issue by skeeperloyaltie** [aimeos/ai-admin-jqadm#291]
**Environment**
1. Version (e.g. 2017.10)
2. Integration (Laravel, TYPO3, Symfony, SlimPHP or Flow)
3. System (Linux, Mac, Windows)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

![image](https://github.com/aimeos/ai-admin-jqadm/assets/54027203/8c003282-6495-44b5-865a-ce2abbeec604)

**Comment by aimeos** [comment]
Please open the browser console and check what happened in the Console and Network tab.
