### ISSUE TITLE
Wrong closing tag in js/components/config-table.js

### ISSUE THREAD

**Issue by edu27** [aimeos/ai-admin-jqadm#292]
https://github.com/aimeos/ai-admin-jqadm/blob/2b610244e1da120f3c1859273c11696f573fe2b3/js/components/config-table.js#L211

Instead of "AimeosMapComponent" should be "AimeosListComponent". This is giving an error in js console.

![imagen](https://github.com/aimeos/ai-admin-jqadm/assets/5015217/4c2cfff4-2176-4623-817f-f2c1a4c5e15d)

**Comment by aimeos** [comment]
You are right and it's now fixed in aimeos/ai-admin-jqadm:2023.10.x-dev
The fix will be in the next package release.

**Comment by edu27** [comment]
Now it's working correctly. Thanks.

**Comment by edu27** [comment]
Now it's working correctly. Thanks.
