### ISSUE TITLE
Deepl not working

### ISSUE THREAD

**Issue by Q4U-mspitz** [aimeos/ai-admin-jqadm#296]
**Environment**
1. Version 2024.04
2. Integration in TYPO3 v12, Plugin v24.4.2
3. System Linux
4. composer installation

**Describe the bug**
The deepl-translation is not working. I configured:
module.tx_aimeos.settings.admin.jqadm.api.translate.key (url also)
In aimeos-Syntax: 
admin/jqadm/api/translate/key

This key is put into the data-attribute "data-translate" as a JSON-String to the <div id="item-text-group" on line 28 in file:
templates/admin/jqadm/attribute/item-text.php
<div id="item-text-group" data-translate="JSON"
This looks fine.

Some other Javascript (I don´t know which one) reads the data and put it as an no-data-attribute to the inner 
<div class="group-list" translate="JSON"

On line 168 of the javascript:
js/apps/text.js
the JS tries to read "this.$el.dataset.translate" on the inner div and that doesnt work. I always get the error: "No Deepl API key..."

**To Reproduce**
1. Edit a product
2. Edit a product-text
3. Click on "Translate" and choose a language
5. See error

**possible solutions**
- access "this.$el.attributes.translate.value" inside the text.js instead of the dataset-attribute
or
- fix the javascript, that transfers the data-attributes from the outer div to the inner non-data-attribute (don´t know where to find)
or
- read the data-attribute of the outer-div

I have not tested OpenAi, but it looks similar and should also not work.

If i use the 1. fix, i get another issue (ContentSecurityPolicy) but this is inside the aimeos-typo3 repository. I open another ticket there (see https://github.com/aimeos/aimeos-typo3/issues/218).

**Comment by aimeos** [comment]
Thank you for the hint! We've fixed the problem in dev-master and 2024.07 branch and it will be part of the next minor 2024.07 release.
