### ISSUE TITLE
BUG IN LARAVEL AIMEOS.

### ISSUE THREAD

**Issue by SarajevoNo1** [aimeos/ai-admin-jqadm#31]
IN LARAVEL AIMEOS!

When I click like admin inside some order in CUSTOMER ID I get this error: 

(1/1) Exception
Not allowed to access JQAdm "customer" client

![image](https://user-images.githubusercontent.com/28009477/38277450-bc5a0c78-3798-11e8-830c-5b4171f16348.png)

thanks

**Comment by aimeos** [comment]
That's because in the admin demo users are not allowed to access the customer panel with user/login data. They would change the login so no one else could log in any more. This is not the case if you install Aimeos on your own.

**Comment by SarajevoNo1** [comment]
Ok thanks great :))))



Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by SarajevoNo1** [comment]
Can We have something in AIMEOS like for example to design mobile cases with images and texts to drag images etc... colors. Text.. like om this site: mycase.rs

Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by aimeos** [comment]
Yes, the frontend detail view has lots of customization options where users can enter custom texts or choose options to customize the product. You only have to implement a possibility to upload an image for the customized mobile case.
