### ISSUE TITLE
Question: Using other admin UI for shop administration

### ISSUE THREAD

**Issue by dev7ch** [aimeos/ai-admin-jqadm#32]
Hello, i would like to try in intergrate the admin theme ( Core UI, Vue), therefore I am a bit unsure what would be the best starting point.

Imagine the scenario to put a new admin theme to aimeo-laravel, how would you start?

-  Option A: Fork this repos and replace allthe views and templates ( would like do avoid that)
-  Option B: Useing the https://github.com/aimeos/ai-admin-jsonadm and new a laravel service provider

How would you start?
I am able to use the https://github.com/aimeos/ai-admin-jsonadm for full aimeos shop functionality?

I would like try avoiding the use of jquery.

It´s just as a test and learning session, maybe for a project, ofc if sth comes out it will be open to everyone

**Comment by aimeos** [comment]
You should create a new extension (e.g. dev7-admin-vue), add any PHP/HTML/Vue.js code there and use the JsonAdm API for retrieving and storing the data you need in your new admin interface implementation

**Comment by dev7ch** [comment]
e.g. how to login and register via jsonadm would be a good stating point i think.

Is the jsonadm full featured for aimeos?  (so I could control Cart, Checkout Wishlist, register, etc all about jsonadm API)

If you would have some links to "headless" example implemeantations, it would be very kindly and helpful.

**Comment by dev7ch** [comment]
i figured out how to acces jsonadm ( e.g. `http://localhost/_prototypes/shop/public/admin/default/jsonadm/customer?id=2`) and json client api.

But i would be very happy if you could give me some tipps how to build a login and auth process.

For now is see in the `users` table only a basic password hash and remember token field, 
I assume the remember token is created by the jqadm during login if the remember option is ticked.

Do you think those fields are enough to ensure a secure login scenario via api?
What do you think about adding an new separate access token for jsonadm ?

**Comment by aimeos** [comment]
The JQAdm interface uses the Json Admin API for several dynamic features like loading categories and fetching data for the charts on demand. The JsonAdm API should be full-featured so you can access the same data as in the JQAdm interface.

The cart is a frontend only thing (but you have access to the orders).

For authentication, you have to look what Laravel offers for API authentication.

**Comment by dev7ch** [comment]
Ok, thank you for the explanations. I ´ll close this issue due there isn´t a specific request.
