### ISSUE TITLE
Mess in category translation

### ISSUE THREAD

**Issue by sergunik** [aimeos/ai-admin-jqadm#34]
Step to reproduce:

1. Go to admin panel and select categories
2. Choose the category you want to change the basic language
3. Change basic language from Dutch to English
4. Check the "text" (translations)
5. French translation is replaced by German, English is replaced by French, German field is missing.
Replaced in current category and others.
![languages bb](https://user-images.githubusercontent.com/1597431/38924657-29c3a1de-4306-11e8-91a9-cb1cb657b1b7.png)
![step 1](https://user-images.githubusercontent.com/1597431/38924661-29fc8422-4306-11e8-9ea7-875ba56d3cde.png)
![step 2](https://user-images.githubusercontent.com/1597431/38924659-29e18a96-4306-11e8-9a6d-56fc5c16e563.png)

**Comment by aimeos** [comment]
You mean when saving the category without changing the texts, they get messed up?

**Comment by sergunik** [comment]
Exactly

**Comment by sergunik** [comment]
aimeoscom/ai-vatcheck (2018.04.4)
aimeos/ai-filesystem (2018.04.1)
aimeos/ai-payments (2018.04.2)
aimeos/ai-admin-jqadm (2018.04.6)
aimeos/ai-admin-jsonadm (2018.04.2)
aimeos/ai-controller-frontend (2018.04.2)
aimeos/ai-controller-jobs (2018.04.2)
aimeos/ai-client-html (2018.04.3)
aimeos/ai-client-jsonapi (2018.04.2)
aimeos/ai-gettext (2018.04.2)
aimeos/ai-laravel (2018.04.1)
aimeos/ai-swiftmailer (2018.04.1)

**Comment by aimeos** [comment]
We don't have that problem in a local test installation. Can you please add some debug output here so we see what happens?

https://github.com/aimeos/ai-admin-jqadm/blob/master/admin/jqadm/src/Admin/JQAdm/Catalog/Text/Standard.php#L367

**Comment by aimeos** [comment]
Do you have details what happens when you save the category? Especially the item data would be interesting
