### ISSUE TITLE
Customer Module access from Orders

### ISSUE THREAD

**Issue by neha023** [aimeos/ai-admin-jqadm#35]
![screenshot-admin demo aimeos org 2018-04-24 18-43-11](https://user-images.githubusercontent.com/22883424/39189471-d669730e-47c1-11e8-9a80-bc3cab86cec8.png)
1. First Problem I have faced that no customer will create from admin panel
2. When go to Ordres and open it not able to see the customer via customer Id.

Please fix these as soon as possible.
Thanks

**Comment by aimeos** [comment]
Duplicate: https://github.com/aimeos/ai-admin-jqadm/issues/31

This is only a problem in the demo because the customer panel is disabled to avoid changes there.
