### ISSUE TITLE
It's possible to create invisible categories in JQAdm

### ISSUE THREAD

**Issue by adimit** [aimeos/ai-admin-jqadm#36]
Steps to reproduce:

- In a fresh Aimeos instance, open JQAdm, navigate to "Categories"
- Click the + to create a new category & save
- Click "cancel" to exit the record
- The newly created category sits at top level
- Without having it selected, click on the '+'
- Create and save another category
- Only the first category is shown

The DB record reads:

```
MariaDB [aimeos]> select id,parentid,level,code,nleft,nright from mshop_catalog;
+----+----------+-------+----------+-------+--------+
| id | parentid | level | code     | nleft | nright |
+----+----------+-------+----------+-------+--------+
| 17 |        0 |     0 | arbeiten |     1 |      2 |
| 18 |        0 |     0 | wohnen   |     3 |      4 |
| 19 |        0 |     0 | foo      |     5 |      6 |
+----+----------+-------+----------+-------+--------+
```

I did this thrice, once with `arbeiten`, once with `wohnen`, and once with `foo`, resulting in 3 top-level categories.

[Screenshot](https://i.imgur.com/LaHzxM3.png) of the interface while the above database record is active.

## Proposed fix:

- If Aimeos supports at max *one* root category (which is OK by me) it should not be possible to create a new root category through the interface
- If Aimeos should support more than one root category, the interface should show all root categories

In the latter case, it should also be possible to drag & drop a category to the root level in the interface. This seems to not currently be the case, as I was unable to pull a child category to root level.

## Using:
```
            "name": "aimeos/ai-admin-jqadm",
            "version": "2018.04.7",
      
            "name": "aimeos/ai-typo3",
            "version": "2018.04.1",

            "name": "aimeos/aimeos-core",
            "version": "2018.04.2",

            "name": "typo3/cms",
            "version": "v8.7.13",
```

**Comment by aimeos** [comment]
Yes, you are right. We will see if all root nodes can be visible

**Comment by adimit** [comment]
Thanks that would be great. It's especially problematic when you accidentally create another root category — you can't see it, you can't delete it, and you can't create a new one with the same code.

**Comment by aimeos** [comment]
Allowing several root nodes had some bad implications in other places so we decided to allow only one category root. This doesn't limit the functionality in any case.

https://github.com/aimeos/aimeos-core/commit/e64aada3780509b58f24d0b3413183baf7e3839f
