### ISSUE TITLE
Attributes Issue

### ISSUE THREAD

**Issue by ClaryPollack** [aimeos/ai-admin-jqadm#37]
When I add multiple texts for an attribute, they all delete when I click "save" with the exception of the last one entered. How can I fix this? Cheers.
Update: I've found a workaround: add new attributes by "type" and delegating the parent item as the type. Thanks again for a great e-commerce platform :)

**Comment by aimeos** [comment]
Guess, you are using 2018.04? We changed to Vue.js beginning of the year and it's not as rock solid as the jQuery/HTML implementation was before. Current dev-master already contains a rewrite for the text handling for products, attributes, catalog and services.

**Comment by aimeos** [comment]
The latest dev-master doesn't show this behavior any more. This will be the base for the upcoming 2018.07 release.
