### ISSUE TITLE
template customization

### ISSUE THREAD

**Issue by sabrine-mg** [aimeos/ai-admin-jqadm#39]
hi, i went to customize the template with my own template but i don't know how even after read the documentation plz i went clear detail

**Comment by aimeos** [comment]
What did you not understand?

**Comment by aimeos** [comment]
What didn't you understand and which template do you want to customize?

**Comment by sabrine-mg** [comment]
i went to insert my own template for disposition of product,cart everything

**Comment by aimeos** [comment]
If you have common questions about customizing Aimeos, please ask you questions in the forum: https://aimeos.org/help/
