### ISSUE TITLE
Get rid of external references by using app.js/css and npm (nodejs)

### ISSUE THREAD

**Issue by Quix0r** [aimeos/ai-admin-jqadm#44]
External JavaScript/CSS references without any security hashes are potential security issues as malicious code could be injected into websites (as browsers load and execute them). It is better (and conform with Laravel's asset system) to have local references that are bundled in `app.css` and `app.js`.

Laravel 5.6 uses NodeJS' `npm` to handle packages. All what you have to do is to add them to `resources/assets/js/app.js` and `resources/assets/sass/app.scss` accordingly.

**Comment by aimeos** [comment]
We had security hashes for all external files until we found out that the Chinese great firewall modifies the external files so browsers doesn't use them. This rendered the admin interface unusable for Chinese developers and shop owners ...

Is resources/assets/js/app.js and resources/assets/sass/app.scss also available in 5.3 till 5.5 which are still supported by Aimeos?

**Comment by Quix0r** [comment]
I'm not sure, if it is.

**Comment by Quix0r** [comment]
Why has it been closed?

**Comment by aimeos** [comment]
As long as it's not supported by 5.3, 5.4 and 5.5 it's not an option at the moment. Some day we will drop support for that versions, then we can use it.

**Comment by Quix0r** [comment]
Before it gets lost, you should then better open it again and add a milestone or so. Then you don't loose track of such future rewrites/features. But it is only a suggestion from me as I have seen it with many other projects.

**Comment by aimeos** [comment]
It's the wrong repository for your issue. Can you please open one in the https://github.com/aimeos/aimeos-laravel repro?

**Comment by Quix0r** [comment]
Done.
