### ISSUE TITLE
uploaded images of products not shown

### ISSUE THREAD

**Issue by sabrine-mg** [aimeos/ai-admin-jqadm#49]
hi, when i try to upload images for products nothing shown
![aim](https://user-images.githubusercontent.com/38504508/42464604-6b80b2a4-835e-11e8-9b9d-351120cba941.PNG)
like this plz help me

**Comment by aimeos** [comment]
Please set APP_URL in your `.env` file correctly, e.g. to "http://localhost:8000/" if you use
```bash
php -S 127.0.0.1:8000 -t public
```
