### ISSUE TITLE
Error on new price

### ISSUE THREAD

**Issue by jonaseberledmind** [aimeos/ai-admin-jqadm#5]
On entering a price, I get the error:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'currencyid' cannot be null, /var/www/playground.schempp-hirth.com/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/DB/Statement/PDO/Simple.php:98 

This is the SQL sent:

```
INSERT INTO "mshop_price" (
                                                "typeid", "currencyid", "domain", "label",
                                                "quantity", "value", "costs", "rebate", "taxrate",
                                                "status", "mtime", "editor", "siteid", "ctime"
                                        ) VALUES (
                                                3, NULL, 'product', '1 :: 1 ~ 120.00 ', 1, '120.00', '0.00', '0.00', '19.00', 1, '2017-07-04 13:52:18', 'j.eberle', 1, '2017-07-04 13:52:18'
                                        )
```

I have only EUR active (It does not show a selector when inserting a new price) - the mshop_locale_currency record looks like this:

`INSERT INTO aimeos.mshop_locale_currency (id, siteid, label, status, mtime, ctime, editor) VALUES ('EUR', 1, 'Euro', 1, '2017-07-04 13:14:23', '2016-06-13 14:41:46', 'j.eberle');
`

**Comment by aimeos** [comment]
Thank you for your bug report. There was indeed a problem when saving products and only one currency is configured. This is fixed now with commit https://github.com/aimeos/ai-admin-jqadm/commit/f04d1517cf651e18d9149d146ebfda044500d30b

Can you confirm that?

**Comment by jonaseberledmind** [comment]
Yes, that works. Thank you for the quick fix!
