### ISSUE TITLE
insert currency issue

### ISSUE THREAD

**Issue by sabrine-mg** [aimeos/ai-admin-jqadm#51]
when i try to add a new currency in admin dashboard this issue is shown " Error An exception occurred while executing ' INSERT INTO "mshop_locale_currency" ( "label", "status", "siteid", "mtime", "editor", "id", "ctime" ) VALUES( 'Tunisian Dinar', 1, 1, '2018-07-12 17:30:57', 'admin', 'TND', '2018-07-12 17:30:57' ) ': SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'TND' for key 'PRIMARY', D:\wamp64\www\myshop\vendor\aimeos\aimeos-core\lib\mwlib\src\MW\DB\Statement\DBAL\Simple.php:97" .

**Comment by aimeos** [comment]
All official currencies are already available. You only have to activiate those you need.
