### ISSUE TITLE
install aimeos without demo

### ISSUE THREAD

**Issue by sabrine-mg** [aimeos/ai-admin-jqadm#54]
**Environment**
1. Version (e.g. 2017.10)
2. Integration (Laravel, TYPO3, Symfony, SlimPHP or Flow)
3. System (Linux, Mac, Windows)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sabrine-mg** [comment]
i installed aimeos without demo section , so when i add a new product from admin dashboard nothing shown and still show this error,tell me what should be to resolve this problem
![demo](https://user-images.githubusercontent.com/38504508/43127566-a133deee-8ee4-11e8-8407-928721785a1a.PNG)

**Comment by aimeos** [comment]
You haven't created a category and you need to add your products to a category so they are shown in the frontend.
