### ISSUE TITLE
user confuse (admin or editor)

### ISSUE THREAD

**Issue by sabrine-mg** [aimeos/ai-admin-jqadm#55]
**Environment**
1. Version (e.g. 2017.10)
2. Integration (Laravel, TYPO3, Symfony, SlimPHP or Flow)
3. System (Linux, Mac, Windows)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by aimeos** [comment]
Thank you for your report. We can confirm the problem and working on a solution.

**Comment by aimeos** [comment]
The problem has been fixed and a new 2018.07 minor version released. Please run "composer update"
