### ISSUE TITLE
upload images not shown

### ISSUE THREAD

**Issue by sabrine-mg** [aimeos/ai-admin-jqadm#56]
**Environment**
1. Version (e.g. 2017.10)
2. Integration (Laravel, TYPO3, Symfony, SlimPHP or Flow)
3. System (Linux, Mac, Windows)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sabrine-mg** [comment]
hi i had upload images from my folder project with aimeos for a such product but not shown in admin dashboard and the catalog list  plz help me i use laragon server ,i had try in env to add localhost:8000 but any result

**Comment by aimeos** [comment]
The ./public/ folder must be your document root available at http://localhost:8000/

**Comment by sabrine-mg** [comment]
what do you mean exactly plz

**Comment by aimeos** [comment]
If you can open http://127.0.0.1:8000/robots.txt of your Laravel application successfully, your images will work too
