### ISSUE TITLE
TND currency

### ISSUE THREAD

**Issue by sabrine-mg** [aimeos/ai-admin-jqadm#57]
**Environment**
1. Version (e.g. 2017.10)
2. Integration (Laravel, TYPO3, Symfony, SlimPHP or Flow)
3. System (Linux, Mac, Windows)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sabrine-mg** [comment]
hi, i  had use the Tunisian currency TND i went the currency shown in catalog list with french (TND) but it shown with arabic as you see in this screen shot
![currency](https://user-images.githubusercontent.com/38504508/43531323-5f9e8b6a-9564-11e8-8207-af7b171e4a96.PNG) plz help with a solution

**Comment by aimeos** [comment]
You can overwrite the currency symbol translation for TND. For details, please ask in the Aimeos forum: https://aimeos.org/help

**Comment by sabrine-mg** [comment]
i had create an account in aimeos help for long time but my account doesn't activated yet that's why i  send my questions here.
