### ISSUE TITLE
theme customization

### ISSUE THREAD

**Issue by sabrine-mg** [aimeos/ai-admin-jqadm#59]
**Environment**
1. Version (e.g. 2017.10)
2. Integration (Laravel, TYPO3, Symfony, SlimPHP or Flow)
3. System (Linux, Mac, Windows)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sabrine-mg** [comment]
hi how i can customize the shop with my own theme ?

**Comment by aimeos** [comment]
Please read this articles: https://aimeos.org/docs/Developers#Frontend
