### ISSUE TITLE
images not shown

### ISSUE THREAD

**Issue by sabrine-mg** [aimeos/ai-admin-jqadm#60]
**Environment**
1. Version (e.g. 2017.10)
2. Integration (Laravel, TYPO3, Symfony, SlimPHP or Flow)
3. System (Linux, Mac, Windows)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sabrine-mg** [comment]
i had use my logo in the header in all pages is the image shown but in the product detail and delivery page not shown

**Comment by aimeos** [comment]
Difficult to say. The page header and structure is provided by Laravel, not by Aimeos
