### ISSUE TITLE
when i can find the error messages

### ISSUE THREAD

**Issue by sabrine-mg** [aimeos/ai-admin-jqadm#61]
**Environment**
1. Version (e.g. 2017.10)
2. Integration (Laravel, TYPO3, Symfony, SlimPHP or Flow)
3. System (Linux, Mac, Windows)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sabrine-mg** [comment]
when i can find the errors messages plz

**Comment by aimeos** [comment]
Error messages for what?
