### ISSUE TITLE
currencies symboles

### ISSUE THREAD

**Issue by sabrine-mg** [aimeos/ai-admin-jqadm#62]
**Environment**
1. Version (e.g. 2017.10)
2. Integration (Laravel, TYPO3, Symfony, SlimPHP or Flow)
3. System (Linux, Mac, Windows)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sabrine-mg** [comment]
hi, i had define the Tunisian dinar as currency but is written with Arabic language i like to be with french language DT not with Arabic plz give me a solution as shown in the picture
![currencies](https://user-images.githubusercontent.com/38504508/44146335-f104eba0-a043-11e8-89d2-1ca3995a36f3.PNG)

**Comment by aimeos** [comment]
Please read this article: https://aimeos.org/docs/Laravel/Overwrite_translations
The translation domain is "currency" and the source string is the three letter ISO currency code.
