### ISSUE TITLE
 Error Item with ID "EN_US" in "locale.language.id" not found

### ISSUE THREAD

**Issue by prosite5** [aimeos/ai-admin-jqadm#64]
unable to manage languages

**Comment by aimeos** [comment]
What host application do you use? Laravel?
Which Aimeos version do you use? 2018.10?

**Comment by prosite5** [comment]
Yes, Larval and Aimeos ~2018.10. When I manage languages and locales, this error occurs. Also, when I open language for editing - code and label fields are empty (but if I look at list, there is data from these fields)

**Comment by prosite5** [comment]
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: nesbot/carbon
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Discovered Package: beyondcode/laravel-dump-server
Discovered Package: nunomaduro/collision
Discovered Package: aimeos/aimeos-laravel
Package manifest generated successfully.
> @php artisan vendor:publish --tag=public --force
Copied Directory [/vendor/aimeos/aimeos-laravel/public] To [/public/packages/aimeos/shop]
Publishing complete.
> @php artisan migrate
Nothing to migrate.

**Comment by prosite5** [comment]
And Is there an ability to add custom content pages and images slider?

**Comment by aimeos** [comment]
Sorry, meant `composer show` ...

Order history is available at the "MyAccount" page, Laravel provides the user registration and login form. For content pages and additional content add more Laravel controllers/actions.

**Comment by prosite5** [comment]
aimeos/ai-admin-jqadm                 2018.10.4 Aimeos ai-admin-jqadm extension
aimeos/ai-admin-jsonadm               2018.10.2 Aimeos ai-admin-jsonadm extension
aimeos/ai-client-html                 2018.10.5 Aimeos ai-client-html extension
aimeos/ai-client-jsonapi              2018.10.3 Aimeos JSON API extension
aimeos/ai-controller-frontend         2018.10.2 Aimeos ai-controller-frontend extension
aimeos/ai-controller-jobs             2018.10.2 Aimeos ai-controller-jobs extension
aimeos/ai-gettext                     2018.10.1 Aimeos Gettext extension
aimeos/ai-laravel                     2018.10.1 Laravel adapter for Aimeos web shops and e-commerce solutions
aimeos/ai-swiftmailer                 2018.10.1 SwiftMailer adapter for Aimeos web shops and e-commerce solutions

aimeos/aimeos-core                    2018.10.4 Full-featured e-commerce components for high performance online shops
aimeos/aimeos-laravel                 2018.10.2 Full-featured Laravel web shop package and e-commerce solution for high performance shops
beyondcode/laravel-dump-server        1.2.2     Symfony Var-Dump Server for Laravel
composer/installers                   v1.6.0    A multi-framework Composer library installer
dnoegel/php-xdg-base-dir              0.1       implementation of xdg base directory specification for php
doctrine/cache                        v1.8.0    Caching library offering an object-oriented API for many cache backends
doctrine/dbal                         v2.8.0    Database Abstraction Layer
doctrine/event-manager                v1.0.0    Doctrine Event Manager component
doctrine/inflector                    v1.3.0    Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                 1.1.0     A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                        v1.0.1    Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
dragonmantank/cron-expression         v2.2.0    CRON for PHP: Calculate the next or previous run date and determine if a CRON expression is due
egulias/email-validator               2.1.6     A library for validating emails against several RFCs
erusev/parsedown                      1.7.1     Parser for Markdown.
fideloper/proxy                       4.0.0     Set trusted proxies for Laravel
filp/whoops                           2.3.1     php error handling for cool kids
fzaninotto/faker                      v1.8.0    Faker is a PHP library that generates fake data for you.
hamcrest/hamcrest-php                 v2.0.0    This is the PHP port of Hamcrest Matchers
jakub-onderka/php-console-color       v0.2
jakub-onderka/php-console-highlighter v0.3.2
laravel/framework                     v5.7.11   The Laravel Framework.
laravel/tinker                        v1.0.8    Powerful REPL for the Laravel framework.
league/flysystem                      1.0.48    Filesystem abstraction: Many filesystems, one API.
mockery/mockery                       1.2.0     Mockery is a simple yet flexible PHP mock object framework
monolog/monolog                       1.23.0    Sends your logs to files, sockets, inboxes, databases and various web services
myclabs/deep-copy                     1.8.1     Create deep copies (clones) of your objects
nesbot/carbon                         1.34.0    A simple API extension for DateTime.
nikic/php-parser                      v4.1.0    A PHP parser written in PHP
nunomaduro/collision                  v2.1.0    Cli error handling for console/command-line PHP applications.
opis/closure                          3.1.1     A library that can be used to serialize closures (anonymous functions) and arbitrary objects.
paragonie/random_compat               v9.99.99  PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phar-io/manifest                      1.0.3     Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                       2.0.1     Library for handling version information and constraints
phpdocumentor/reflection-common       1.0.1     Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock     4.3.0     With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a ...
phpdocumentor/type-resolver           0.4.0
phpspec/prophecy                      1.8.0     Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage             6.1.3     Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator             2.0.2     FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template             1.2.1     Simple template engine.
phpunit/php-timer                     2.0.0     Utility class for timing
phpunit/php-token-stream              3.0.0     Wrapper around PHP's tokenizer extension.
phpunit/phpunit                       7.4.3     The PHP Unit Testing framework.
psr/container                         1.0.0     Common Container Interface (PHP FIG PSR-11)
psr/http-message                      1.0.1     Common interface for HTTP messages

psr/log                               1.0.2     Common interface for logging libraries
psr/simple-cache                      1.0.1     Common interfaces for simple caching
psy/psysh                             v0.9.9    An interactive shell for modern PHP.
ramsey/uuid                           3.8.0     Formerly rhumsaa/uuid. A PHP 5.4+ library for generating RFC 4122 version 1, 3, 4, and 5 universally unique identifiers (UUID).
sebastian/code-unit-reverse-lookup    1.0.1     Looks up which function or method a line of code belongs to
sebastian/comparator                  3.0.2     Provides the functionality to compare PHP values for equality
sebastian/diff                        3.0.1     Diff implementation
sebastian/environment                 3.1.0     Provides functionality to handle HHVM/PHP environments
sebastian/exporter                    3.1.0     Provides the functionality to export PHP variables for visualization
sebastian/global-state                2.0.0     Snapshotting of global state
sebastian/object-enumerator           3.0.3     Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector            1.1.1     Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context           3.0.0     Provides functionality to recursively process PHP variables
sebastian/resource-operations         2.0.1     Provides a list of PHP built-in functions that operate on resources
sebastian/version                     2.0.1     Library that helps with managing the version number of Git-hosted PHP projects
swiftmailer/swiftmailer               v6.1.3    Swiftmailer, free feature-rich PHP mailer
symfony/console                       v4.1.6    Symfony Console Component
symfony/css-selector                  v4.1.6    Symfony CssSelector Component
symfony/debug                         v4.1.6    Symfony Debug Component
symfony/event-dispatcher              v4.1.6    Symfony EventDispatcher Component
symfony/finder                        v4.1.6    Symfony Finder Component
symfony/http-foundation               v4.1.6    Symfony HttpFoundation Component
symfony/http-kernel                   v4.1.6    Symfony HttpKernel Component
symfony/polyfill-ctype                v1.9.0    Symfony polyfill for ctype functions
symfony/polyfill-mbstring             v1.9.0    Symfony polyfill for the Mbstring extension
symfony/polyfill-php72                v1.9.0    Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/process                       v4.1.6    Symfony Process Component
symfony/psr-http-message-bridge       v1.1.0    PSR HTTP message bridge
symfony/routing                       v4.1.6    Symfony Routing Component
symfony/translation                   v4.1.6    Symfony Translation Component
symfony/var-dumper                    v4.1.6    Symfony mechanism for exploring and dumping PHP variables
theseer/tokenizer                     1.1.0     A small library for converting tokenized PHP source code into XML and potentially other formats
tijsverkoyen/css-to-inline-styles     2.2.1     CssToInlineStyles is a class that enables you to convert HTML-pages/files into HTML-pages/files with inline styles. This is very useful w...
vlucas/phpdotenv                      v2.5.1    Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
webmozart/assert                      1.3.0     Assertions to validate method input/output with nice error messages.
zendframework/zend-diactoros          1.8.6     PSR HTTP Message implementations

**Comment by aimeos** [comment]
Looks OK. What's the error message and the stack trace in the log panel?

**Comment by aimeos** [comment]
Issue has been fixed (https://github.com/aimeos/ai-admin-jqadm/commit/b5f26a5921d8788cc74b25216ea2535ba5ef57c6) and will be part of the release next week
