### ISSUE TITLE
Route [] not defined.

### ISSUE THREAD

**Issue by prosite5** [aimeos/ai-admin-jqadm#66]
when I try to add a product and then open page /list it shows me "A non-recoverable error occured", and I have found in log table Route [myrote] not defined. How to solve?

**Comment by prosite5** [comment]
hm, yes. I specified a custom name for the page. Or maybe I had to register this route somewhere in routes/web.php before? Does not admin add the routes dymamically?

**Comment by aimeos** [comment]
No, the Aimeos admin interface is unable to do that
