### ISSUE TITLE
Sort product images in backend

### ISSUE THREAD

**Issue by dertimon** [aimeos/ai-admin-jqadm#68]
![aimeos](https://user-images.githubusercontent.com/449505/48762335-1c1c9c80-ecab-11e8-9d3d-ed4f99008a0c.jpg)
The order of product images in the aimeos backend cannot be changed.
It would be nice if one could change the order by drag and drop just like the categories.

**Comment by aimeos** [comment]
Yes, that would be nice :-)

**Comment by aimeos** [comment]
The infrastructure for sorting images, texts, prices, etc. is already available using the Sorting.js library. It's currently deactiviated because there have been problems with updating the position entries.

**Comment by aimeos** [comment]
This has been implemented now and will be available in the next release:
https://github.com/aimeos/ai-admin-jqadm/commit/8248a2da51654e4aaefbe6d8f7b2dd8f6b545778
