### ISSUE TITLE
Feature request: Products "save and stay"

### ISSUE THREAD

**Issue by jonaseberledmind** [aimeos/ai-admin-jqadm#7]
When entering products one would often want to save and check the changes in the frontend.

With more products, finding the product again can be a bit of a hassle.

I'd like to see a "save & stay" function. I'd even say that it could be the standard action.

**Comment by aimeos** [comment]
This is already the case in almost all integrations. For TYPO3 it's now also available if you install the latest version.

**Comment by jonaseberledmind** [comment]
You are totally amazing!!!
