### ISSUE TITLE
Unable to delete attribute image

### ISSUE THREAD

**Issue by noll1** [aimeos/ai-admin-jqadm#70]
**Environment**
1. ai-admin-jqadm: 2018.10.7; aimeos-core: 2018.10.10
2. Integration: TYPO3 v9.5.1
3. System: Ubuntu 18.04.1

**Describe the bug**
When I want to remove a image from an attribute I get an error message.

**To Reproduce**
1. Go to attribute "Demo: Black".
2. Change to image tab.
3. Remove the image.
4. Click save

**Expected behavior**
The image should be deleted after saving.

**Screenshots**
![attr_img_delete](https://user-images.githubusercontent.com/42864489/49638364-3f17b200-fa08-11e8-81a0-ef8f120e0378.png)

**Comment by aimeos** [comment]
Thank you for your bug report! We can confirm the issue.
It has been fixed in dev-master and 2018.10-dev branch and will be part of the next release

**Comment by noll1** [comment]
Thank you! I'll be waiting for it.
