### ISSUE TITLE
Association between variant and select remains after type change

### ISSUE THREAD

**Issue by noll1** [aimeos/ai-admin-jqadm#71]
**Environment**
1. Version: 2018.10.2
2. Integration: TYPO3
3. System: Ubuntu 18.04.1

**Describe the bug**
When I change the product type from "select" to "default" the association to the variant products will not be deleted.

**To Reproduce**
1. Create a select product with a variant.
2. Set to both one picture.
3. When you look to the select product in the frontend it has 2 pictures (one from itself and one from variant).
4. Change the product type from "select" to "default".
5. The old select product still has both images.

**Expected behavior**
After change the type from "select" to "default" all association should be dissolved.

**Comment by aimeos** [comment]
This patch should fix the problem of your old images: https://github.com/aimeos/ai-client-html/commit/9ba8e65348eaf952f100245456b1a6083707a99b

**Comment by noll1** [comment]
Thanks for the quick help!
