### ISSUE TITLE
Orders hidden payment attributes visible after saving

### ISSUE THREAD

**Issue by noll1** [aimeos/ai-admin-jqadm#72]
**Environment**
1. Version: 18.10.2
2. Integration: TYPO3
3. System: Ubuntu 18.04.1

**Describe the bug**
I've written my own payment provider where I save hidden attributes to the order if the payment is finished.
I achieve that with following function:
![save_pay_attr](https://user-images.githubusercontent.com/42864489/49877511-da07f600-fe25-11e8-8600-50326b737b0e.png)
Because of the "hidden" keyword the attributes won't be shown in users order history but are only accessible in the order overview of the backend.
Up to here everything is fine.
Now I change the status of a product in an order (e.g. from "unfinished" to "deleted").
After this all attributes that where hidden before are now displayed in the order history of the user.
I think after saving the order the hidden attributes are switched to normal ones.

**Expected behavior**
Attributes that have already been saved should not change their type after the order has been saved again.

**Comment by aimeos** [comment]
Issue has been fixed and will be part of the next release: https://github.com/aimeos/ai-admin-jqadm/commit/72900a61bcb8d5d0374888ab68a754f418551e6a

**Comment by noll1** [comment]
Thanks for solving!
