### ISSUE TITLE
Can't delete product with download

### ISSUE THREAD

**Issue by noll1** [aimeos/ai-admin-jqadm#73]
**Environment**
1. Version: 18.10.2
2. Integration: TYPO3
3. System: Ubuntu 18.04.1

**Describe the bug**
When I try to delete a product which has a download file attached I get following error:
Error Couldn't delete file "test", /var/www/typo3/typo3conf/ext/aimeos/Resources/Libraries/aimeos/aimeos-core/lib/mwlib/src/MW/Filesystem/Standard.php:159

**To Reproduce**
1. Create a product with a download file.
2. Delete the product.

**Comment by aimeos** [comment]
Thank you for your bug report! Seems like you are testing all dark corners of the Aimeos admin interface ;-)
Issue has been fixed and will be part of the release today: https://github.com/aimeos/ai-admin-jqadm/commit/78ea4b345e66b5a3cd58719bf3f0bf66412b44ec

**Comment by noll1** [comment]
Sorry for flooding you with tickets ;-D
Problem solved.
