### ISSUE TITLE
uploaded product's images are not shown

### ISSUE THREAD

**Issue by lamaf90** [aimeos/ai-admin-jqadm#79]
**Environment**
1. Version: 2018.10
2. Integration: Symfony
3. System: Windows

**Describe the bug**
Hi, I have created a new product but the images uploaded are not shown in administration interface. Please help, thank you!

**Expected behavior**
show uploaded images in administration interface

**Screenshots**
![image](https://user-images.githubusercontent.com/45677971/50356343-e260df00-0551-11e9-823e-2ac8e42e44ed.png)

**Comment by aimeos** [comment]
You've installed Aimeos in a subdirectory, you you have to adapt the client/html/common/content/baseurl to your real path in your config file (depends on your Symfony version)

**Comment by lamaf90** [comment]
Thank you for your help. I have tried to adapt the client/html/common/content/baseurl to my real path in my config file as shown attached but I still have the same problem.

![image](https://user-images.githubusercontent.com/45677971/50375473-1db8e780-05fe-11e9-9354-4132afe3350c.png)

However, I notice that after uploaded my images they are saved automatically in different directories located in two others named "files" and "preview" which were automatically created. I don't really understand that behavior. May be the problem.

![image](https://user-images.githubusercontent.com/45677971/50375705-49d66780-0602-11e9-8bac-f7e892b809c0.png)

**Comment by lamaf90** [comment]
Hi, thank you for your help. I did exactly what you suggested but I still have the problem. I also don't  understand why my files are not saved in the folder configured (localhost/aimeos/web/uploads/images). Please any idea?

**Comment by adetheprince** [comment]
client/html/common/content/baseurl  I dont have this on my aimeos fresh install.
I am using Symfony 5 , installed this to my server view composer.

/var/www/html/myshop/

I dont have these folders you mentioned so I guess I am using a different version?

I downloaded from you https://github.com/aimeos/aimeos  so how can edit BaseUrl and use a correct paths if someone installed it in sub folder like me.

**Comment by aimeos** [comment]
Symfony 5 isn't officially supported due to the FOSUserBundle isn't available for Symfony 5.
The URL is the Laravel 6 based Aimeos distribution.

In case of Laravel, please adapt the APP_URL setting in the .env file of your installation to your used URL.

**Comment by adetheprince** [comment]
Yeah thanks not sure about the version I was using, but I have edited the .env file and set the path mywebsite.com instead if localhost:8000, and it works.
Thanks for your response.
