### ISSUE TITLE
Feature request: Hide select boxes with only 1 option

### ISSUE THREAD

**Issue by jonaseberledmind** [aimeos/ai-admin-jqadm#8]
For example in "Stock" I guess a standard configuration normally would only have 1 StockType: "Standard".

It could save a little if that was preselected, because it is a) a mandatory field and b) there is only 1 option.

**Comment by aimeos** [comment]
Thank your for your suggestion. The stock type is now hidden if only one is available (17962d3db0e522ec37b9159f98d25fbd814234dc)

**Comment by jonaseberledmind** [comment]
Wow! Thanks! I can confirm it already works :)
