### ISSUE TITLE
Order Plugin Configuration Options in Admin added too often / duplicated

### ISSUE THREAD

**Issue by AndreasA** [aimeos/ai-admin-jqadm#81]
**Environment**
1. Version 2018.10.13
2. Integration TYPO3
3. System Linux

**Describe the bug**
When adding an order plugin, after choosing a plugin type the corresponding configuration is added multiple times. There seem to be multiple reasons for this:
1. Too often / soon queried against the configuration interface. I nearly always get the config at least twice, e.g. for autocomplete this makes sense but for config I guess it might be enough upon leaving the field (or at least after a minor timeout).
2. It seems the query is always done onblur which results that if one enteres and leaves and enters and leaves the field, the corresponding config options are always added again.
3. It doesn't check if a config has already been added before re-adding / appending it.

**To Reproduce**
1. Go into the aimeos backend.
2. Go to Plugins.
3. Click the "Plus" icon to a dd a new one.
4. Select a plugin type. This usually results in the config being added twice.

5. Leave the field.
6. Re-Enter the field.
7. Leave again without modifications.
8. Now the configuration options are added again too.

**Expected behavior**
Only add new configuration options and ensure config options aren't queried that often too.

**Comment by aimeos** [comment]
Confirmed

**Comment by aimeos** [comment]
The issue has been fixed with commits https://github.com/aimeos/ai-admin-jqadm/commit/f71bfb91b876b121ac5a8e2a81fd9f570bc99444 and https://github.com/aimeos/ai-admin-jqadm/commit/d032f7c69d78acd58a1b8cdad957729f4c902cf7 and will be part of the next release
