### ISSUE TITLE
User Lookup By Admin Code

### ISSUE THREAD

**Issue by Jawnzard** [aimeos/ai-admin-jqadm#84]
**Environment**
1. Version (2018.10.3)
2. Integration (Laravel)
3. System (Linux)

**Describe the bug**
Hello, I just installed Aimeos and followed the demo setup and everything. So far it seems to be working beautifully but I noticed that on the admin side when I try to filter customers by "Group code" with value "admin" I get a SQL error. Apologies if this is just a configuration issue or if problem exists between keyboard and chair.

**To Reproduce**
1. Go to the admin section
2. Click on 'Customers'
3. Expand the search parameters in the top right
4. Select "Group code" for the filter (I used operator "=~" and "admin" for the value)
5. Received the SQL error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'mcusgr.code' in 'where clause', /var/www/aimeos/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/DB/Statement/DBAL/Simple.php:91

**Expected behavior**
Expected a filtered list of customers who are members of the group having a code value of "admin"

**Screenshots**

**Additional context**
I checked my MySQL logs and found the trouble query:
SELECT COUNT(*) AS "count"
FROM (
SELECT DISTINCT lvu."id"
FROM "users" AS lvu
WHERE ( ( ( mcusgr."code" LIKE 'admin%' ESCAPE '#' ) AND 1 = 1 ) )
LIMIT 10000 OFFSET 0
) AS list

**Comment by aimeos** [comment]
Thank you for your bug report!

The problem is that we can't filter customers by group at all because there's no parent/child relationship between them. We will to remove that filter option in the next version.

Alternatively, we can offer to fetch the groups a user belongs to and display them in the list but you won't be able to filter/sort by group name.

**Comment by Jawnzard** [comment]
Ah ok, I see that now after digging through the database schema a bit more. Thank you for the prompt response!
