### ISSUE TITLE
Only one coupon code visible in order view

### ISSUE THREAD

**Issue by BU-Andi** [aimeos/ai-admin-jqadm#85]
If you purchase more than one online coupon code, only the first is visible in the order view.

![screenshot_2019-02-15 15 43 03_f4wpro](https://user-images.githubusercontent.com/47667285/52863583-950b8300-3138-11e9-92b8-f2f78db5e1fe.png)

**Comment by aimeos** [comment]
Thank you for the hint. The improvement will be part of the next Aimeos version and we've add some more improvements when the coupons get generated: https://github.com/aimeos/ai-client-html/commit/d1ad8ab35cb39156993b085f01ffe20604c62fd2
