### ISSUE TITLE
Coupon code filter in order listing

### ISSUE THREAD

**Issue by BU-Andi** [aimeos/ai-admin-jqadm#86]
There is no possibility to map purchased coupon codes to the order.
It would be nice to have a coupon code filter option in the order listing.

![screenshot_2019-02-15 15 48 58_ko8pln](https://user-images.githubusercontent.com/47667285/52863903-41e60000-3139-11e9-9a5a-7731ae7eba1f.png)

**Comment by aimeos** [comment]
Thank you for your suggestion. It has been implemented and will be part of the next release: https://github.com/aimeos/ai-admin-jqadm/commit/3a1f1ea85e67fd9473f01bbf2e8063c6e331987c
