### ISSUE TITLE
please provide a overall video tutorial on YouTube so that easily we can create product, categories everything ..... Thank You 

### ISSUE THREAD

**Issue by aminulbinnoor** [aimeos/ai-admin-jqadm#87]
**Is your feature request related to a problem?**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**
Any alternative solutions or features you've considered?

**Additional context**

**Comment by aimeos** [comment]
We may do this in the future

**Comment by applavictoria** [comment]
Hi, I installed Aimeos for Typo3.
The documentation that I found, are versions of typo3 6.2 of the year 2014.
I would like to see it in the video / documentation:
1.- scheduller, like and order.
2.- create a simple structure of products.
I am creating a web of food, both dishes and ingredients, recipes, mixtures of spices, dressings ...
an example where you can create a category, product and components.

**Comment by aimeos** [comment]
Several videos are now available and we continue to add new ones:
https://youtube.com/c/aimeos
