### ISSUE TITLE
Product image upload resets title

### ISSUE THREAD

**Issue by nvindice** [aimeos/ai-admin-jqadm#88]
**Environment**
1. Version: 2018.10.14
2. Integration: Typo3

**Describe the bug**
When we upload an image and set the title, the title is not stored in the database. It gets stored only if the image is already saved an the title is changed afterwards.

**To Reproduce**
1. Open product, go to "Images"
2. Click "add"
3. Choose image
4. Enter "Title"
5. Click "Save"
-> Title was not saved, but the original image file name.

**Expected behavior**
The title should be stored in database right away.

**Comment by aimeos** [comment]
Thank you for your bug report, we can confirm the issue

**Comment by aimeos** [comment]
Issue has been fixed and will be part of the next release: https://github.com/aimeos/aimeos-core/commit/d223d6280fb9faa9d0a157d81e1d09dbd7878d40
