### ISSUE TITLE
the subcategories are not shown in the front-end.. HELP ME PLEASE!

### ISSUE THREAD

**Issue by josegbv** [aimeos/ai-admin-jqadm#89]
**Environment**
1. Version (e.g. 2017.10)
2. Integration (Laravel, TYPO3, Symfony, SlimPHP or Flow)
3. System (Linux, Mac, Windows)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by josegbv** [comment]
Environment

Version ultimate
Integration (Laravel)
System ( Windows)

here the error  https://drive.google.com/file/d/1eKJ8AG7BbF4pXewd3zD8NCZUh0bkPhBz/view
                         https://drive.google.com/file/d/1tbMjdb748ZVdtLARq_7WdcPdTJ8YYpsD/view

**Comment by aimeos** [comment]
We have no access to your screenshots
