### ISSUE TITLE
add logout

### ISSUE THREAD

**Issue by nandanvrs** [aimeos/ai-admin-jqadm#9]
please add log out option in admin area

**Comment by aimeoscom** [comment]
Unfortunately, that isn't that easy as it sounds to get this to work for all integrations

**Comment by aimeos** [comment]
We've added a Logout link in the Laravel template that everyone can adapt (https://github.com/aimeos/aimeos-laravel/commit/205ce10976e3e42eefa625ef39f2eb81d522444b). It's not great from a visual point of view but works:
![admin-logout](https://user-images.githubusercontent.com/8647429/29033024-e9707196-7b93-11e7-9e1d-40a0a388f226.png)
