### ISSUE TITLE
Product characteristics can not be saved (JS problem)

### ISSUE THREAD

**Issue by nvindice** [aimeos/ai-admin-jqadm#92]
**Environment**
1. Version: 2018.10
2. Integration: Typo3
3. System: Debian

**Describe the bug**
Sometimes, when changing an existing product attribute after copying a product (at Product > Characteristics), the new value from the dropdown will not be stored in the hidden select field. Then, the product can't be saved (because it is has the required-tag), and there is no error visible (because it is hidden).

**To Reproduce**
1. Create a product with an attribute
2. Copy the product - do not save yet!
3. Go to Characteristics -> change the existing attribute
4. Click "save"
Sometimes the error occurs, sometimes not. Hard to find out why.

**Expected behavior**
Saving without an error :-)

**Comment by aimeos** [comment]
We couldn't reproduce the problem, even after intense testing. A possible problem is if you type in the attribute name but don't select the item in the list. Then, the combobox contains text only (which is only for informational purpose and in prinicple irrelevant) but not the ID of the attribute in the hidden field which is updated by the handler for the "onSelect" event.

**Comment by aimeos** [comment]
Some commits from the last few days improve indicating errors and prevent invalid attribute selections and duplicate selections. It should now be much harder for editors to make mistakes.
