### ISSUE TITLE
In the Products list, provide the option to show the "categories"

### ISSUE THREAD

**Issue by rowild** [aimeos/ai-admin-jqadm#96]
**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
In the produc list, the columns shown can be changed (as per the documentation here: https://aimeos.org/docs/User_Manual/Administration_Interface/Filtering_lists, under "Changing columns shown"). It would be great to have an option that would show the categories the product belongs to.

**Describe alternatives you've considered**
No alternatives

**Additional context**
No additional context.

**Comment by aimeos** [comment]
Categories are not attached to products so this way is difficult

**Comment by rowild** [comment]
...well, but it would be most useful, wouldn't it?
So I gather that category:product is 1:n? No chance to extend this to m:n?
Or is there a completely different relation structure implemented?

**Comment by aimeos** [comment]
Yes, there are case where it would be useful to have that information in the product list.
The database structure is:
mshop_catalog -> mshop_catalog_list.refid (points to mshop_product.id for products)
The catalog and product domain are completely separate, so there are no joins possible to get that information quickly.

**Comment by rowild** [comment]
Thank you for the insight and information!
I still would like to see this feature implemented one day, so I leave this request open. But please feel free to close it, if it is not on you top priorities list!
(Should I ever be able to provide a PR, I will do that.)

**Comment by aimeos** [comment]
Waiting for your pull request
