### ISSUE TITLE
jqtree loses and regains "selected" state on toggling

### ISSUE THREAD

**Issue by rowild** [aimeos/ai-admin-jqadm#97]
When a level-2 subcategory is clicked on, it shows the "selected" state by displaying a blue vertical bar on the left site of the category name. Clicking on the category again (and moving away with the mouse) removes the selected state, clicking again (and moving the mouse away) re-establishes the active state again.

This seems to happen only on categories from level 2 on.
TYPO3 9.5, aimeos 19.7, php 7.2, Chrome 77

This is not really important, as no functionality is influenced by that (as far as I see), but for the sake of completeness it should be mentioned here.

**Comment by aimeos** [comment]
Tested this using the dev-master version and the problem seems to be gone
