### ISSUE TITLE
Image Upload via Admin for Products

### ISSUE THREAD

**Issue by kibitok** [aimeos/ai-admin-jqadm#99]
**Environment**
1. Version (e.g. 2017.10)
2. Integration (Laravel, TYPO3, Symfony, SlimPHP or Flow)
3. System (Linux, Mac, Windows)

**Describe the bug**
The Image is not fully loaded when uploaded under the product section

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Products
2. Click on + icon
3. Scroll down to images
4. Upload Product image
5. Save the Image
6. See error

**Expected behaviour**
An image of the product added.

**Screenshots**
![Screenshot from 2019-10-09 12-35-45](https://user-images.githubusercontent.com/27912414/66469846-547ac400-ea91-11e9-8d89-233e62de7b78.png)

**Comment by aimeos** [comment]
Please adapt the `APP_URL` setting in your `.env` file and include the port (8000) you are using.

**Comment by kibitok** [comment]
Sorry for checking in late. 
The problem still persists.

I have changed the APP_URL as you have suggested.
![Screenshot from 2019-10-15 08-42-52](https://user-images.githubusercontent.com/27912414/66803339-feda6780-ef27-11e9-8d31-0710dddd2818.png)


this is how it appears at the backend
![Screenshot from 2019-10-09 12-35-45](https://user-images.githubusercontent.com/27912414/66803438-44973000-ef28-11e9-8d40-48739d6b38d2.png)

At the front-end
![Screenshot from 2019-10-15 08-33-46](https://user-images.githubusercontent.com/27912414/66803446-524cb580-ef28-11e9-9b89-97ce7511dfd6.png)

**Comment by kibitok** [comment]
![Screenshot from 2019-10-15 09-20-38](https://user-images.githubusercontent.com/27912414/66805231-1ec05a00-ef2d-11e9-80c5-2253730c9a17.png)

**Comment by aimeos** [comment]
Is there an error in the browser console? How does the <img> tag for that missing image look like?

**Comment by kibitok** [comment]
Managed the issue by reserving the server. Thanks

**Comment by adetheprince** [comment]
Managed the issue by reserving the server? what does that mean I have the same issue too please help.
